### ISSUE TITLE
老哥有考虑增加自动分割功能吗?

### ISSUE THREAD

**Issue by yukminnie** [auqhjjqdo/LiveRecorder#102]
### 直播平台

支持的所有平台

### 需求描述

我网络挺稳定的, 我算了一下, 有些主播如果连播十几个小时, 最后录制视频可能得有六七十个G. 

有没有考虑添加类似30分钟自动分割, 然后重新请求新直播流进行录制的功能.

### 操作步骤（可选）

1.检测录制时长
2.断开录制
3.重新请求新直播源进行录制

**Comment by auqhjjqdo** [comment]
这个是后期软件做的事，不是录制软件应有的功能

**Comment by NormanMises** [comment]
这个自己改ffmpeg的代码可以实现
