### ISSUE TITLE
pandalive 被风控禁了？

### ISSUE THREAD

**Issue by NormanMises** [auqhjjqdo/LiveRecorder#104]
### 运行环境

版本号：
运行平台：
运行架构：
Python版本：

### 配置文件

```JSON
a
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/38835726/6f1c6383-758a-4aab-8484-a9e56f6113a0)
用了一段时间cookies之后就获取不到流了，网页上所有直播都打不开，显示观看被禁止

### 错误日志

```Text
q
```

**Comment by jimmy0435** [comment]
我也遇到一樣問題
感覺可能是api請求太多被禁了

**Comment by NormanMises** [comment]
太惨了账号直接废掉了

**Comment by xueli12** [comment]
换代理应该就可以了吧？

**Comment by NormanMises** [comment]
> 换代理应该就可以了吧？

不管用 账号被禁了
