### ISSUE TITLE
抖音录制画质非最高码率

### ISSUE THREAD

**Issue by xueli12** [auqhjjqdo/LiveRecorder#108]
### 运行环境

版本号：2.3.3
运行平台：win10
运行架构：x86
Python版本：3.12

### 配置文件

```JSON
{
    "proxy": "http://127.0.0.1:7897",
    "output": "output",
    "user": [
        {
            "platform": "Douyin",
            "id": "456066026839",
            "name": "douyin测试1",
            "cookies": "ttwid=XXXX",
            "output": "C:/record/KBJ/Douyin/测试",
            "interval": 60,
            "format": "flv",
        },
        {
            "platform": "Douyin",
            "id": "456066026839",
            "name": "douyin测试2",
            "output": "C:/record/KBJ/Douyin/测试",
            "interval": 60,
            "format": "flv",
        }

    ]
}
```

### 复现步骤（可选）

1.分别使用了登录后的cookie和不填cookie
2.
3.
...

### 错误描述

使用cookie和不使用cookie下载的视频画质是一样的，码率大概都是5000多，经分析，flv_pull_url中并不包含原画画质的视频流
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/51438016/c8fd2193-5a59-4a37-9243-37c1750fea7e)

下面这两个为使用其他两个不同的程序录制的视频的码率信息，均为原画画质：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/f51ba4f7-cc64-4b4a-8cc6-28d73aaee5cb)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/3419e362-fd00-46a2-a8e9-660eb2343889)

最后附上能获取到douyin原画直播流的项目的代码供作者大大参考：

第一个是https://github.com/biliup/biliup/blob/master/biliup/plugins/douyin.py
其中biliup这段代码的逻辑是在原画获取不到时会优先选最低一档的画质，建议在参考biliup代码的的基础上在origin画质获取不到时选择uhd画质，从高到低选择

第二个是
https://github.com/hr3lxphr6j/bililive-go/blob/master/src/live/douyin/douyin.go
看不太懂代码

### 错误日志

```Text
无报错，只是视频画质非最高码率
```

**Comment by auqhjjqdo** [comment]
v2.35已修复
