### ISSUE TITLE
一直报直播检测请求错误

### ISSUE THREAD

**Issue by qq654387964** [auqhjjqdo/LiveRecorder#13]
直播检测请求错误
ConnectError('[Errno 11001] getaddrinfo failed

**Comment by auqhjjqdo** [comment]
配置文件写错了，发一下我看看

**Comment by qq654387964** [comment]
麻烦 大佬帮忙看下

 

 

 

 

 

发件人: auqhjjqdo ***@***.***> 
发送时间: 2023年5月26日 17:07
收件人: auqhjjqdo/LiveRecorder ***@***.***>
抄送: qq654387964 ***@***.***>; Author ***@***.***>
主题: Re: [auqhjjqdo/LiveRecorder] 一直报直播检测请求错误 (Issue #13)

 

配置文件写错了，发一下我看看

**Comment by auqhjjqdo** [comment]
你发了个什么？请在github issue页面回复

**Comment by qq654387964** [comment]
{
  "proxy": "http://127.0.0.1:7890",
  "user": [
    {
      "platform": "Bilibili",
      "id": "15152878",
      "name": "鹿乃",
      "interval": 10,
      "format": "mp4",
      "headers": {
        "Referer": "https://live.bilibili.com/"
      },
      "cookies": "SESSDATA=xxxxx; bili_jct=xxxxx"
    },
    {
      "platform": "Douyu",
      "id": "101",
      "name": "PDD"
    },
    {
      "platform": "Huya",
      "id": "991111",
      "name": "TheShy"
    },
    {
      "platform": "Youtube",
      "id": "UCShXNLMXCfstmWKH_q86B8w",
      "name": "斑比鹿乃"
    },
    {
      "platform": "Twitch",
      "id": "kanotic_",
      "name": "桜帆鹿乃"
    },
    {
      "platform": "Twitcasting",
      "id": "kano_2525",
      "name": "鹿乃",
      "interval": 8
    },
    {
      "platform": "Afreeca",
      "id": "legendhyuk",
      "name": "legendhyuk"
    }
  ]
}
  配置文件

**Comment by auqhjjqdo** [comment]
请将`config.json`按照示例文件`config.sample.json`修改成自己需要录制的直播之后再运行，并注意proxy代理部分是否需要填写，无需代理请直接删除proxy字段
