### ISSUE TITLE
[Bug]:斗鱼录制报错 

### ISSUE THREAD

**Issue by jieli1990** [auqhjjqdo/LiveRecorder#14]
### 运行环境

版本号：
运行平台：win10
运行架构：
Python版本：
3.10

### 配置文件

```JSON
{
  "user": [
    {
      "platform": "Douyu",
      "id": "92000",
      "name": "610"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

Client error '404 Not Found' for url 'https://open.douyucdn.cn/api/RoomApi/room/92000'

### 错误日志

2023-06-01 14:45:57.218 | ERROR    | __main__:start:51 - [Douyu][610]直播检测请求状态码错误
Client error '404 Not Found' for url 'https://open.douyucdn.cn/api/RoomApi/room/92000'
For more information check: https://httpstatuses.com/404
"Not Found"

**Comment by auqhjjqdo** [comment]
`92000`应该是斗鱼的房间号短号，真实房间号是`2947432`，即打开`https://www.douyu.com/92000`后重定向的网站地址里`rid=`后面的数字，将配置文件的id部分修改为真实房间号即可

**Comment by jieli1990** [comment]
感谢

**Comment by jieli1990** [comment]
问题解决
