### ISSUE TITLE
申请抖音直播录制功能

### ISSUE THREAD

**Issue by supercell532** [auqhjjqdo/LiveRecorder#16]
**直播平台**

**需求描述**

**操作步骤**

**Comment by ashen9** [comment]
抖音录制，format字段不起作用，最终始终是flv格式

**Comment by auqhjjqdo** [comment]
> 抖音录制，format字段不起作用，最终始终是flv格式

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/7bc77489-f97f-4874-aa1f-a0f45975ad3b)
无法复现，请单独发issue提供相关日志和复现步骤

**Comment by maxchiron** [comment]
Ctrl+C not invoke ffmpeg pack in Ubuntu22.04 LTS WLS2
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/85681332/91b272a3-bcf0-4925-944e-ed9b725bb2b8)

**Comment by auqhjjqdo** [comment]
> Ctrl+C not invoke ffmpeg pack in Ubuntu22.04 LTS WLS2 ![image](https://user-images.githubusercontent.com/85681332/247139320-91b272a3-bcf0-4925-944e-ed9b725bb2b8.png)

我在debian 11的服务器上测试能正常捕获ctrl+c中断请求，wsl环境比较特殊我无法测试，请确认streamlink也能捕获到ctrl+c，另外wsl的[issue](https://github.com/microsoft/WSL/issues/7959)存在相关讨论，不排除是wsl自身问题

**Comment by auqhjjqdo** [comment]
> > > Ctrl+C not invoke ffmpeg pack in Ubuntu22.04 LTS WLS2 ![image](https://user-images.githubusercontent.com/85681332/247139320-91b272a3-bcf0-4925-944e-ed9b725bb2b8.png)
> > 
> > 
> > 我在debian 11的服务器上测试能正常捕获ctrl+c中断信号，wsl环境比较特殊我无法测试，请确认streamlink也能捕获到ctrl+c，另外wsl的[issue](https://github.com/microsoft/WSL/issues/7959)存在相关讨论，不排除是wsl自身问题 请尽量使用windows平台版本，特殊环境不单独支持
> 
> okay, thanks for your distribution. I'll try this later on a real Ubuntu server. BTW, how could I make sure the streamlink can get ctrl+c?

streamlink是一个python编写的的cli程序，详情可查看[streamlink官方文档](https://streamlink.github.io/cli.html)

**Comment by maxchiron** [comment]
> > > > Ctrl+C not invoke ffmpeg pack in Ubuntu22.04 LTS WLS2 ![image](https://user-images.githubusercontent.com/85681332/247139320-91b272a3-bcf0-4925-944e-ed9b725bb2b8.png)
> > > 
> > > 
> > > 我在debian 11的服务器上测试能正常捕获ctrl+c中断信号，wsl环境比较特殊我无法测试，请确认streamlink也能捕获到ctrl+c，另外wsl的[issue](https://github.com/microsoft/WSL/issues/7959)存在相关讨论，不排除是wsl自身问题 请尽量使用windows平台版本，特殊环境不单独支持
> > 
> > 
> > okay, thanks for your distribution. I'll try this later on a real Ubuntu server. BTW, how could I make sure the streamlink can get ctrl+c?
> 
> streamlink是一个python编写的的cli程序，详情可查看[streamlink官方文档](https://streamlink.github.io/cli.html)

thanks~
