### ISSUE TITLE
[Bug]: 录制AFreeca报错 PluginError: Unable to open URL: http://livestream-manager.afreecatv.com

### ISSUE THREAD

**Issue by SingleRottenChips** [auqhjjqdo/LiveRecorder#19]
### 运行环境

版本号：2.16
运行平台：Win10
运行架构：Windows
Python版本：3.11

### 配置文件

```JSON
{
  "proxy": null,
  "output": "output",
  "user": [
    {
      "platform": "Afreeca",
      "id": "xxxxxxxxx",
      "name": "xxxxxxxxx",
	  "interval": 10,
      "format": "mp4",
      "headers": {
        "Referer": "https://play.afreecatv.com/"
      }
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

用Streamlink也报了相同错误，所以我猜这里是cookies这项没填的缘故。请问该怎么填，哪里找？

另外，我是用谷歌账号登陆Afreeca的，username我用“找回用户名”功能收邮件确认过，但是用”找回密码“却提示邮箱不存在... 我用谷歌密码填password那一项，报登陆失败。请问有什么办法吗？

### 错误日志

PluginError("Unable to open URL: http://livestream-manager.afreecatv.com/broad_stream_assign.html (('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))")
Traceback (most recent call last):

  File "urllib3\connectionpool.py", line 790, in urlopen

  File "urllib3\connectionpool.py", line 536, in _make_request

  File "urllib3\connection.py", line 454, in getresponse

  File "http\client.py", line 1375, in getresponse

  File "http\client.py", line 318, in begin

  File "http\client.py", line 279, in _read_status

  File "socket.py", line 705, in readinto

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by auqhjjqdo** [comment]
网络连接相关错误，非程序自身问题，请确保本地网络能访问报错信息中的网址，注意是否需要设置代理

**Comment by SingleRottenChips** [comment]
> 网络连接相关错误，非程序自身问题，请确保本地网络能访问报错信息中的网址，注意是否需要设置代理

好的。我现在填了代理地址，无误（yt-dlp正常使用）但是现在报无法打开此链接了：http://live.afreecatv.com/afreeca/player_live_api.php。另外我尝试把上面那个网址和这个都在Clash上添加规则，上面能用Chrome打开了，尽管提示 not found; 但这个网址和cmd一样报 502 error...

**Comment by auqhjjqdo** [comment]
报not found是指没找到网页，在没有网址参数的情况下是正常现象，说明服务器是正常响应的，至于502报错，如果一直出现那就是服务器问题，也有可能是代理节点的问题

**Comment by SingleRottenChips** [comment]
> 报not found是指没找到网页，在没有网址参数的情况下是正常现象，说明服务器是正常响应的，至于502报错，如果一直出现那就是服务器问题，也有可能是代理节点的问题

代理节点没有问题... 因为不挂代理，第一个网址也是报502，但挂了就能打开了。然而现在是第二个网址报502了。

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/e9597cd9-f9bf-426b-9c92-69ce67709a16)
我这边测试无任何问题，请自行解决网络问题

**Comment by SingleRottenChips** [comment]
>我这边测试无任何问题，请自行解决网络问题
把 live.com 和 livestream-manager.afreecatv.com 添加 DOMAIN-SUFFIX 规则后解决了，当时傻了没事先查看走流量的域名，怕加了会走代理流量，把那两个网址加了DOMAIN规则...
