### ISSUE TITLE
录制文件放置在对应文件夹中，例如“output/平台-主播名/xxx.flv”

### ISSUE THREAD

**Issue by thermalme** [auqhjjqdo/LiveRecorder#21]
**直播平台**
抖音、斗鱼等
**需求描述**
目前录制的视频都是统一存放在“output”文件夹中，能否按照“平台-主播名”建立文件夹，将对应主播的视频统一放置在对应文件夹中，方便管理。
**操作步骤**
无

**Comment by auqhjjqdo** [comment]
已在新版本中添加针对单个用户的output字段，请自行修改配置文件实现所述功能

**Comment by thermalme** [comment]
> 已在新版本中添加针对单个用户的output字段，请自行修改配置文件实现所述功能

谢谢作者大大，辛苦了！
