### ISSUE TITLE
[Bug]: pluggingerror

### ISSUE THREAD

**Issue by ripperX309** [auqhjjqdo/LiveRecorder#22]
### 运行环境

版本号：v2.17
运行平台：windows11
运行架构：x86
Python版本：3.9

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:7890",
  "output": "E:/AfreecaTv",
  "user": [
    {
      "platform": "Bilibili",
      "id": "15152878",
      "name": "鹿乃",
      "interval": 10,
      "format": "mp4",
      "output": "bilibili_鹿乃",
      "proxy": null,
      "headers": {
        "Referer": "https://live.bilibili.com/"
      },
      "cookies": "SESSDATA=xxxxx; bili_jct=xxxxx"
    },
    {
      "platform": "Douyu",
      "id": "101",
      "name": "PDD"
    },
    {
      "platform": "Huya",
      "id": "991111",
      "name": "TheShy"
    },
    {
      "platform": "Douyin",
      "id": "282773369501",
      "name": "央视新闻"
    },
    {
      "platform": "Youtube",
      "id": "UCShXNLMXCfstmWKH_q86B8w",
      "name": "斑比鹿乃"
    },
    {
      "platform": "Twitch",
      "id": "kanotic_",
      "name": "桜帆鹿乃"
    },
    {
      "platform": "Afreeca",
      "id": "in0074",
      "name": "荷恩",
      "interval": 30,
      "format": "mp4",
      "output": "E:/AfreecaTv",
      "proxy": "http://127.0.0.1:7890",
      "headers": {
        "Referer": "https://www.afreecatv.com/"
      },
      
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

配置好后运行提示streamlink.exceptions.PluginError: Unable to open URL: http://live.afreecatv.com/afreeca/player_live_api.php (502 Server Error: Bad Gateway for url: http://live.afreecatv.com/afreeca/player_live_api.php)
请问这是streamlink插件的问题吗？

### 错误日志

Traceback (most recent call last):

  File "main.py", line 397, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 49, in start

  File "main.py", line 367, in run

  File "streamlink\session.py", line 614, in streams

  File "streamlink\plugin\plugin.py", line 428, in streams

  File "C:\Users\10638\AppData\Local\Temp\_MEI384282\streamlink\plugins\afreeca.py", line 203, in _get_streams
    channel = self._get_channel_info(bno, username)
              │    │                 │    └ 'in0074'
              │    │                 └ '247090511'
              │    └ <function AfreecaTV._get_channel_info at 0x0000021983CC4430>
              └ <streamlink.plugins.afreeca.AfreecaTV object at 0x000002198396EA70>

  File "C:\Users\10638\AppData\Local\Temp\_MEI384282\streamlink\plugins\afreeca.py", line 115, in _get_channel_info
    res = self.session.http.post(self.CHANNEL_API_URL, data=data)
          │    │       │    │    │    │                     └ {'bid': 'in0074', 'bno': '247090511', 'from_api': '0', 'mode': 'landing', 'player_type': 'html5', 'pwd': '', 'stream_type': '...
          │    │       │    │    │    └ 'http://live.afreecatv.com/afreeca/player_live_api.php'
          │    │       │    │    └ <streamlink.plugins.afreeca.AfreecaTV object at 0x000002198396EA70>
          │    │       │    └ <function Session.post at 0x0000021980128670>
          │    │       └ <streamlink.plugin.api.http_session.HTTPSession object at 0x00000219819236A0>
          │    └ <streamlink.session.Streamlink object at 0x0000021981922DD0>
          └ <streamlink.plugins.afreeca.AfreecaTV object at 0x000002198396EA70>

  File "requests\sessions.py", line 637, in post

  File "streamlink\plugin\api\http_session.py", line 183, in request

streamlink.exceptions.PluginError: Unable to open URL: http://live.afreecatv.com/afreeca/player_live_api.php (502 Server Error: Bad Gateway for url: http://live.afreecatv.com/afreeca/player_live_api.php)

**Comment by auqhjjqdo** [comment]
https://github.com/auqhjjqdo/LiveRecorder/issues/19

**Comment by auqhjjqdo** [comment]
请仔细阅读readme，cookie一般用于需要用户登录的付费内容直播，游客能正常播放直播时无需cookie，请勿原封不动抄写示例配置

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/7fdb1ab9-2568-4823-911a-7507b748822e)
实测在正确添加cookie后能正常录制该直播，请注意cookie是否完整

**Comment by ripperX309** [comment]
重新检查发现cookies少打了个o，现在正常了。再请教一下我明明可以直连观看afreecatv直播，为什么这里录制在clash中不更改为使用代理就无法连接上了呢？

**Comment by auqhjjqdo** [comment]
afreecatv的网页似乎并没被墙，但获取直播信息的接口http://live.afreecatv.com/afreeca/player_live_api.php在国内是被墙的，所以需要使用代理
