### ISSUE TITLE
抖音的录制视频只能播放音频

### ISSUE THREAD

**Issue by BingoZha** [auqhjjqdo/LiveRecorder#23]
### 运行环境

版本号：[v20230418](https://github.com/LyzenX/DouyinLiveRecorder/releases/tag/v20230418)
运行平台：win10
运行架构：cmd
Python版本：Python 3.10.9

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:7890",
  "output": "output",
  "user": [
    {
      "platform": "Douyin",
      "id": "301152964459",
      "name": "xxx"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

General
Complete name                  : E:\Code\py\record\LiveRecorder\output\[2023.07.01 21.46.03][Douyin]...
Format                         : Flash Video
File size                      : 60.8 MiB
Duration                       : 35 min 51 s
Overall bit rate               : 237 kb/s
_is_hardware_encode            : 1.000
_qId                           : BlackFrameOptimization
_Encoder                       : bytedmediasdkios:NKhB6Wu20KECcBV/0VWIVxmWxWZJyjFM5faVZkJkKj9ZlBZp883hmdw1DTSxzl3r1r2K6VDIl+1nVJrSkstTIeONANBrWmixzFzCuSidYt07OO4fcrWH+Of07zRALlON
_sdk_version                   : 13.7.0.7-aweme
_model                         : iPhone 11
_signResult                    : {"frametype":"1","lid":"712198790","signversion":"1.0","signinfo":"f710788a7ddb2d9a1354a97a6560a9a0a0ed035150bcf18cb1347dce4d60f896fbb76630060ff040499fd9c01c6caffafb72bab6d381f816e21012340e71839193e2e079e656b283bc98f9259957c1d9f74e1c3a038b9c47f939ccea7e1afcb80af4803b358190b502d04b67eec6c4f95720a2e31b718a059ccf1b952aa98d9dda809cf505e1fb16934ce0075033b89e617b968a2c600457be5f5ef893867807","signvalue":"1b3fad8eb7139e71971a8fd5f191a27a117dfe6fec81279ca86aed4e7fcddbd8","dynamicinfo":"13911616ebac900f0576d19c438844cd"}
_link_info                     : n.cn-29dddv.wa2g_15095,n.cn-xlop26.6z5l_319562,n.cn-xlop26.psax_3935840
_hit_node_optimize             : 1.000
_interval                      : 2.000
_default_bitrate               : 930.000
_publish_time_stamp            : 1688217266
_min_bitrate                   : 930.000
_os_version                    : 15.1
_push_protocol                 : rtmp
_start_time                    : 1688219110823.000
_max_bitrate                   : 2438.000
_platform                      : iOS
_stream_id                     : push-rtmp-hs-f5.douyincdn.com:stagereplay:stream-113294342438781615

Video
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main@L4@Main
Codec ID                       : 12
Duration                       : 35 min 51 s
Bit rate                       : 2 441 kb/s
Width                          : 1 088 pixels
Height                         : 1 920 pixels
Display aspect ratio           : 0.567
Frame rate mode                : Constant
Frame rate                     : 20.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Bits/(Pixel*Frame)             : 0.058
Stream size                    : 626 MiB

Audio
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : HE-AAC / LC
Codec ID                       : 10
Duration                       : 35 min 51 s
Bit rate                       : 62.5 kb/s
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 44.1 kHz / 22.05 kHz
Frame rate                     : 21.533 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 28 ms
Stream size                    : 16.0 MiB (26%)

### 错误日志

[2023-07-01 21:46:01][INFO][__main__][start:46][Douyin][xxx]正在检测直播状态
[2023-07-01 21:46:03][INFO][__main__][run_record:131][Douyin][xxx]开始录制：[2023.07.01 21.46.03][Douyin][xxx]xxx.flv
[2023-07-01 21:46:03][INFO][__main__][stream_writer:143][Douyin][xxx]获取到直播流链接：[2023.07.01 21.46.03][Douyin][xxx]xxx.flv
http://pull-flv-f26.douyincdn.com/stagereplay/stream-113294342438781615.flv
[2023-07-01 21:46:04][INFO][__main__][stream_writer:149][Douyin][xxx]正在录制：[2023.07.01 21.46.03][Douyin][xxx]xxx.flv
[2023-07-01 21:55:48][INFO][__main__][run_record:138][Douyin][xxx]停止录制：[2023.07.01 21.46.03][Douyin][xxx]xxx.flv
[2023-07-01 21:56:00][INFO][__main__][run_record:131][Douyin][xxx]开始录制：[2023.07.01 21.56.00][Douyin][xxx]xxx.flv
[2023-07-01 21:56:00][INFO][__main__][stream_writer:143][Douyin][xxx]获取到直播流链接：[2023.07.01 21.56.00][Douyin][xxx]xxx.flv
http://pull-flv-f1.douyincdn.com/stagereplay/stream-113294342438781615.flv
[2023-07-01 21:56:01][INFO][__main__][stream_writer:149][Douyin][xxx]正在录制：[2023.07.01 21.56.00][Douyin][xxx]xxx.flv

**Comment by auqhjjqdo** [comment]
所以这是个什么bug能不能描述一下

**Comment by BingoZha** [comment]
抱歉，刚才光顾着填后面的信息了，标题忘记补全了。。。
是这样，抖音录制的视频用Kmplayer播放的时候只有音频，后来我看了一下视频属性，是有视频流的。
后来换了另外一个播放器可以播放，可能是缺少解码器的关系。

**Comment by BingoZha** [comment]
还有一个问题，抖音录制的时候经常断一般是什么原因

**Comment by auqhjjqdo** [comment]
抖音的直播流默认是flv格式的，理论上所有播放器都能正常播放，播不了与录制脚本无关，你可以添加format参数在录制结束就自动封装成其他格式
录制中断我测试并没出现，请先确保你的网络无问题
