### ISSUE TITLE
是否可以增加清晰度选择的选项呢？

### ISSUE THREAD

**Issue by hyizhou** [auqhjjqdo/LiveRecorder#26]

**Comment by auqhjjqdo** [comment]
因为不同平台对清晰度的定义不一样，streamlink对各大直播平台的清晰度名字并不一致，只有`best`和`worst`是固定值，加上部分主播的直播间并没有画质切换（例如哔哩哔哩的部分直播仅原画可看），清晰度选择的选项不能很好的做到统一，而且斗鱼和抖音平台streamlink并不支持，这需要对代码进行大量重构才能实现
此外录播的作用一般是用于存档，大多数情况下仅需存储最高画质即可，有其他画质需求可以对最高画质存档使用ffmpeg进行转码，所以目前暂不考虑添加清晰度选择支持
