### ISSUE TITLE
[Bug]: 抖音的视频总是出问题

### ISSUE THREAD

**Issue by End-Satan** [auqhjjqdo/LiveRecorder#27]
### 运行环境

版本号：
运行平台：windows-debian
运行架构：
Python版本：

### 配置文件

```JSON
{
      "platform": "Douyin",
      "id": "400461848178",
      "name": "懿玉",
      "format": "flv"
    },
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

抖音的视频本地windows系统potplayer能播放但是debian自带的播放器无法播放。我上传到youtube测速也是无法播放。测试了多个格式都是这样的情况

### 错误日志

无

### 错误截图（可选）

![QQ截图20230709223609](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/28e756ba-55cf-4d96-b07c-25aba56dfa04)

**Comment by auqhjjqdo** [comment]
potplayer能播放说明录制文件并没损坏，只是录制的格式在别的播放器上缺少解码器，尝试将format参数改为mp4进行自动封装

**Comment by End-Satan** [comment]
> potplayer能播放说明录制文件并没有损坏，只是改为录制的格式在其他播放器上丢失解码器，尝试将格式参数mp4进行自动封装

已经测试过了mp4.avi.ts.都是这样。

**Comment by auqhjjqdo** [comment]
我看了下抖音录制文件的编码信息，视频流使用的是H.265编码，并非常规的H.264编码，这种编码格式在很多平台是不兼容的，你需要在对应平台下载支持H.265解码的播放器或者使用ffmpeg将vcodec参数改为libx264再重新转码才能正常播放，视频编码相关问题并非录播bug

**Comment by End-Satan** [comment]
> 我看了下抖音录制文件的编码信息，视频流使用的是H.265编码，并非常规的H.264编码，这种编码格式在很多平台是不兼容的，你需要在对应平台下载支持H.265解码的播放器或者使用ffmpeg将vcodec参数改为libx264再重新转码才能正常播放，视频编码相关问题并非录播bug

。。听的似懂非懂。请问搜啥关键词可以学习下

**Comment by auqhjjqdo** [comment]
> > 我看了下抖音录制文件的编码信息，视频流使用的是H.265编码，并非常规的H.264编码，这种编码格式在很多平台是不兼容的，你需要在对应平台下载支持H.265解码的播放器或者使用ffmpeg将vcodec参数改为libx264再重新转码才能正常播放，视频编码相关问题并非录播bug
> 
> 。。听的似懂非懂。请问搜啥关键词可以学习下

https://www.videosolo.com/zh-CN/tutorials/h.265-player.html

**Comment by End-Satan** [comment]
> > > 我看了下抖音录制文件的编码信息，视频流使用的是H.265编码，并非常规的H.264编码，这种编码格式在很多平台是不兼容的，你需要在对应平台下载支持H.265解码的播放器或者使用ffmpeg将vcodec参数改为libx264再重新转码才能正常播放，视频编码相关问题并非录播bug
> > 
> > 
> > 。。听的似懂非懂。请问搜啥关键词可以学习下
> 
> https://www.videosolo.com/zh-CN/tutorials/h.265-player.html

你好，这个如何播放我是知道，我是想了解下如何把抖音录制的视频转换为正常的视频，因为我想上传到油管这样就能随时随地在线播放了。

**Comment by End-Satan** [comment]
> > > 我看了下抖音录制文件的编码信息，视频流使用的是H.265编码，并非常规的H.264编码，这种编码格式在很多平台是不兼容的，你需要在对应平台下载支持H.265解码的播放器或者使用ffmpeg将vcodec参数改为libx264再重新转码才能正常播放，视频编码相关问题并非录播bug
> > 
> > 
> > 。。听的似懂非懂。请问搜啥关键词可以学习下
> 
> https://www.videosolo.com/zh-CN/tutorials/h.265-player.html

我测试了下通过插件获取抖音直播流下载地址，通过下载下来的直播视频上传油管却能正常播放。。

**Comment by End-Satan** [comment]
> 请分别发一下使用录播脚本录制的文件和插件获取的直播流文件的视频编码信息，potplayer播放时按TAB键即可显示，另外提供一下插件的链接
插件我用的是cococut老版本（旧版本可以看到下载链接）https://t.wss.ink/f/bo12oyyxko3 复制链接到浏览器打开
![捕获](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/d2dc3442-480b-4bfc-9ec3-0da4d8faf1eb)
这个是脚本录制的。
![2](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/46cf39ca-64fb-43a9-b352-56c94ddfa16e)
这个是下载的

**Comment by auqhjjqdo** [comment]
发了一个新版本优化了一下视频编码选择，欢迎尝试并反馈问题

**Comment by End-Satan** [comment]
> 发了一个新版本优化了一下视频编码选择，欢迎尝试并反馈问题

config的格式好像之前的用不了
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/39c3468a-97fc-4ed0-8cda-c3eb4fe78503)
这个原本是可以正常录制的，更新后就不行

**Comment by End-Satan** [comment]
![捕获](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/5dbcf78f-6d91-4d94-84b3-3d0d3d51ff1f)
```
{
  "output": "output",
  "user": [
    {
      "platform": "Douyu",
      "id": "290935",
      "name": "周淑怡"
    },
    {
      "platform": "Douyu",
      "id": "4624967",
      "name": "腐团"
    },
    {
      "platform": "Douyin",
      "id": "231640982929",
      "name": "水淼淼"
    }
  ]
}
```

**Comment by End-Satan** [comment]
看了下，提示错误的是不在线的主播，主播在线的还是正常下载

**Comment by auqhjjqdo** [comment]
主播开播判断重新优化了一下，尝试一下新版本

**Comment by End-Satan** [comment]
> 主播开播判断重新优化了一下，尝试一下新版本

今天斗鱼的直播流出问题了。
![捕获](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/9f23e2af-6986-4365-92eb-0af6d0ee67d3)
