### ISSUE TITLE
装最新版本httpcore的话 这个库会报错

### ISSUE THREAD

**Issue by Co1dF1sh** [auqhjjqdo/LiveRecorder#3]

**Comment by Co1dF1sh** [comment]
试了一下前面的几个版本 都不行 报的错还不一样 不知道作者用的哪个版本

**Comment by auqhjjqdo** [comment]
发一下具体报错日志

**Comment by Co1dF1sh** [comment]
Traceback (most recent call last):
  File "###/LiveRecorder/main.py", line 12, in <module>
    from httpx_socks import AsyncProxyTransport
  File "###/LiveRecorder/venv/lib/python3.9/site-packages/httpx_socks/__init__.py", line 11, in <module>
    from ._sync_transport import SyncProxyTransport
  File "###/LiveRecorder/venv/lib/python3.9/site-packages/httpx_socks/_sync_transport.py", line 2, in <module>
    from httpcore._backends.sync import SyncSocketStream  # noqa
ModuleNotFoundError: No module named 'httpcore._backends'

**Comment by auqhjjqdo** [comment]
我这边测试Release里打包好的二进制都能正常运行没有报依赖错误，如果你是源码安装请检查pip install是否有报错

**Comment by Co1dF1sh** [comment]
> 

pip install没有问题
应该就是库的版本的问题。requirements.txt里面没有标这些库的版本，所以在pip install的时候全都默认装的最新的库，而这个httpcore的库我去翻了下文档，一直在大改，所以有些调用的东西没了。
所以作者大大能给个httpcore库的版本号吗，应该换个对应的版本就能解决😭

**Comment by auqhjjqdo** [comment]
如果是想魔改源码，你最好在虚拟venv环境pip install，全局安装可能会引起依赖混乱导致报错，而且Release打包的版本也是直接pip install的，具体可以看https://github.com/auqhjjqdo/LiveRecorder/blob/main/.github/workflows/build.yml#L31

**Comment by auqhjjqdo** [comment]
另外httpx官方是限制了httpcore的版本，所以你不能直接安装httpcore的新版本
参考https://github.com/encode/httpx/blob/master/pyproject.toml#L32

**Comment by Co1dF1sh** [comment]
> 另外httpx官方是限制了httpcore的版本，所以你不能直接安装httpcore的新版本
> 参考https://github.com/encode/httpx/blob/master/pyproject.toml#L32

感谢
