### ISSUE TITLE
文档中没有具体用法示例?

### ISSUE THREAD

**Issue by xjl456852** [auqhjjqdo/LiveRecorder#33]
**直播平台**

**需求描述**
可以写几个用法示例,最简化的配置,命令用法,是否需要参数等等,现在的文档看完后,不知道如何使用.
**操作步骤**

**Comment by auqhjjqdo** [comment]
请仔细阅读readme，你所提到的在文档中都有，config.sample.json即简单配置示例，仅需添加你需要录播的平台和主播即可
