### ISSUE TITLE
增加弹幕和礼物的录制功能

### ISSUE THREAD

**Issue by niu-github** [auqhjjqdo/LiveRecorder#34]
**直播平台**
抖音

**需求描述**
请问是否能够增加弹幕和礼物的录制(记录)功能，或者单独保存为xml或json的文件

**操作步骤**

**Comment by auqhjjqdo** [comment]
程序并非录屏而是直接下载直播流，因此无法做到实时弹幕滚动的录制
弹幕和礼物录制由于涉及websocket相关技术，且各家弹幕的协议不尽相同，需要对代码进行大量重构，现阶段是保证直播录制稳定性，如确有需要欢迎pr
