### ISSUE TITLE
是否支持暂停和持续的增加任务?

### ISSUE THREAD

**Issue by xjl456852** [auqhjjqdo/LiveRecorder#35]
**直播平台**
所有平台
**需求描述**
1.视频流暂停下载:在下载视频流的过程中如果需要突然暂停录制,然后过一会再接着录制,视频可以追加到原始的视频文件中.
2.如果有个直播突然比较感兴趣,如何在其它任务执行中,增加新的视频流下载任务,而不干扰其它的任务.
3.是否可以暂停或停止任务中的某一个视频流下载任务.
感谢软件开发人员的无私奉献.
**操作步骤**

**Comment by auqhjjqdo** [comment]
1.本项目仅用于无人值守自动录制，录制暂停得到的文件你可以通过后期剪辑实现
2.由于配置文件是在程序启动时读取，中途添加直播用户则需要实时监控文件变化并动态添加，会影响到无人值守录制稳定性
3.录制任务由streamlink接管，线程运行过程不能随意停止，否则会容易引发程序崩溃
综上所述，暂不考虑添加此类功能，如确有需求可以pr
