### ISSUE TITLE
[Enhancement]: 实时状态的输出

### ISSUE THREAD

**Issue by Xian0Grem** [auqhjjqdo/LiveRecorder#38]
### 直播平台

ALL

### 需求描述

有时候网络抽风会导致短暂掉线。日志只输出报错而不输出重连，我无法判断它是否正在正常工作

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
轮询机制即自带重试效果，程序的运行逻辑如下：
请求接口判断是否开播->网络出错自动重试5次，5次请求失败抛出错误日志->检测到开播后启动新线程调用streamlink录制直播->录制过程网络出错由streamlink抛出错误->退出线程重新轮询直播检测请求接口
因此只要你不主动终止程序，重试机制即实时生效，所以网络问题会导致录制文件出现零散分段，这是所有直播录制软件的通病，如果你有其他解决思路欢迎提出

**Comment by Xian0Grem** [comment]
原来如此，只要不持续报错就是正常工作
