### ISSUE TITLE
[Enhancement]: 终止录播功能

### ISSUE THREAD

**Issue by 1068093640** [auqhjjqdo/LiveRecorder#39]
### 直播平台

所有平台

### 需求描述

添加一个可以在录播的时候提前终止的功能吧

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
在运行界面按下ctrl+c即可中断录制并自动封装，这是通用的中断程序快捷键，如果无需封装直接关闭程序即可
