### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by lhs55502002** [auqhjjqdo/LiveRecorder#4]
为什么设置好后打开是这样：

Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "httpx_socks\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "httpx_socks\_sync_transport.py", line 2, in <module>
ModuleNotFoundError: No module named 'httpcore._backends'
[5608] Failed to execute script 'main' due to unhandled exception!

[已退出进程，代码为 1 (0x00000001)]

<img width="884" alt="屏幕截图 2023-04-16 143844" src="https://user-images.githubusercontent.com/62332619/232277602-ec989fa6-ddf4-45c7-a614-0e9e263df034.png">

**Comment by auqhjjqdo** [comment]
重新运行了下github actions，不知道为什么打包出错了，你试试新打包的版本

**Comment by lhs55502002** [comment]
> 重新运行了下github actions，不知道为什么打包出错了，你试试新打包的版本

能下是能下，就是下载的视频有些播放不了，出现如图的提示。而且如果想中断的话不知道怎么中断，我是按ctrl+c中断的，但是这样的话下载的视频就看不了了，也是出现如图的提示：
<img width="523" alt="屏幕截图 2023-04-16 204818" src="https://user-images.githubusercontent.com/62332619/232312659-cfb8c170-cc42-4d1b-a40f-e7a5e104585f.png">
这些是测试下载的，只有一个能看
<img width="969" alt="屏幕截图 2023-04-16 204801" src="https://user-images.githubusercontent.com/62332619/232312724-f782b5a5-9847-46ed-89c4-1d8cc196c897.png">

**Comment by auqhjjqdo** [comment]
播不了那就是未正常关闭文件损坏了，crtl+c存在关闭视频流的校验问题，不能中断的话就直接点X关闭吧，不保证一定不会损坏
想彻底解决的话就在源码里改成输出ts格式，mp4就得自己ffmpeg封装了

**Comment by lhs55502002** [comment]
> 播不了那就是未正常关闭文件损坏了，crtl+c存在关闭视频流的校验问题，不能中断的话就直接点X关闭吧，不保证一定不会损坏 想彻底解决的话就在源码里改成输出ts格式，mp4就得自己ffmpeg封装了

能说一下怎么改成ts格式吗？我没学过编程的东西，streamlink,yt-dlp等都是看教程弄的。我还是改成ts格式稳点吧，毕竟直播只能录一次，稳定很重要。

**Comment by auqhjjqdo** [comment]
更新了自定义输出格式的配置，你可以尝试使用新版本修改为ts格式

**Comment by lhs55502002** [comment]
能看是能看了，但是怎么不连续了。如图，试了一个直播，下成了两个文件。我检查了，中间一段时间没录上。
<img width="930" alt="屏幕截图 2023-04-17 174622" src="https://user-images.githubusercontent.com/62332619/232452563-4459d4ff-ad39-4fdb-98f0-24b31c18d1fa.png">
下图是exe的记录
<img width="997" alt="2023-04-17_174538" src="https://user-images.githubusercontent.com/62332619/232453321-e5994107-b3cc-4310-a293-fe8865855c2c.png">


这让我想起了分割功能的问题。如果有按时间分割的功能应该比较好吧？防止一个错误导致全部录制丢失。streamlink不知道有没有按自定义时间分割片段，我找了下streamlink的命令没找到。如果streamlink没有我觉得您可以加一下这个功能。

而且我想问为什么不弄一个直接调用streamlink的脚本呢？我对编程了解不多，我只是想提出我的一个想法，如果不能实现，您别介意。比如我想录制油管的直播，用streamlink的话只需要在cmd输入命令：”streamlink youtuber的主页链接“，而用你的程序就要设置platform,id,name,header,cookies等等，虽然必填只有两个,但是其他东西可以在streamlink的config里设置。也就是说 ，如果你能弄成直接调用streamlink的话，就只需要设置主播的主页和检测是否直播的时间间隔（当然，时间间隔可以用另外的东西检测，不然直接输入到streamlink的话费时会比较长）。

**Comment by auqhjjqdo** [comment]
这个是你自己的梯子网络丢包导致的，长时间没有获取到直播流数据，超过了设定的超时时间就会停止录制，丢包导致的直播数据丢失所有软件都不能做到恢复，时间分割也不行
录制直播是不知道主播什么时候下播的，只能通过设置超时的方式来停止录制，streamlink自己也是这样实现停止录制的
关于调用streamlink的质疑，这个脚本本来就是全程调用streamlink来录制的，只是在录制之前加入了对目标平台的开播判断实现自动录制
streamlink自己也有循环重试然后录制的参数，但是存在一些问题，比如无法获取到直播间标题，多次录制不区分文件名会覆盖同名文件，自动ffmpeg封装，不能录制youtube的多开直播间等

**Comment by lhs55502002** [comment]
好的，我不知道原来streamlink有这些问题。我几次用streamlink 都能完整的录下来，而用你的程序就不行，所以我以为是你的程序的问题。如果是vpn的问题就麻烦了，因为好的vpn不好找，要么就是贵。我用的是clash。
