### ISSUE TITLE
[Enhancement]: 要是能有手动暂停功能就好啦

### ISSUE THREAD

**Issue by FightForMyself** [auqhjjqdo/LiveRecorder#41]
### 直播平台

虎牙

### 需求描述

能有手动暂停功能就好了

### 操作步骤（可选）

1.
2.
3.
...

### 需求截图（可选）

能有手动暂停功能就好了

**Comment by auqhjjqdo** [comment]
https://github.com/auqhjjqdo/LiveRecorder/issues/35
