### ISSUE TITLE
[Bug]: Linux ARM 下执行出错

### ISSUE THREAD

**Issue by LidoCKT** [auqhjjqdo/LiveRecorder#42]
### 运行环境

版本号：2.21
运行平台：Ubuntu
运行架构： ARM64
Python版本：Release的可执行程序 (但有Python 3.8.10

### 配置文件

```JSON
{
  "proxy": null,
  "output": "output",
  "user": [
    {
      "platform": "Youtube",
      "id": "UCRILJB5Cy5Qd33h_f61f1Vg",
      "name": "Seventeen"
    }
  ]
}
```

### 复现步骤（可选）

1.解压
2.编写config.json
3.   ./LiveRecorder
...

### 错误描述

跳错无法执行（在Win11下同配置文件正常运行）

### 错误日志

```Text
ubuntu@xxx:~/LiveRecorder$ ./LiveRecorder
APPRUN_ERROR: No such file or directoryubuntu@xxx:~/LiveRecorder$
```

**Comment by auqhjjqdo** [comment]
appimage打包跨架构导致的问题，由于我没有实测环境无法复现该报错，请优先使用源码运行方式，自建python虚拟环境理论可以支持所有平台
