### ISSUE TITLE
请求添加 pandalive 直播平台

### ISSUE THREAD

**Issue by justdoiting** [auqhjjqdo/LiveRecorder#43]
### 直播平台

pandalive

### 需求描述

在GitHub上面搜了很久，只有一个能获取直播源的工具，而且是rust语言的，不知道是不是可以借鉴一下转换成Python达到下载直播的目的

相关项目   https://github.com/Borber/seam/blob/master/crates/core/src/live/panda.rs

### 操作步骤（可选）

1.借鉴rust的开源项目转换成Python语言
2.整合到该项目
3.支持下载pandalive平台
...

**Comment by auqhjjqdo** [comment]
已添加Pandalive，请尝试新版本

**Comment by justdoiting** [comment]
> 已添加Pandalive，请尝试新版本

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/9ddfd1a4-ccc8-4da4-b0d9-fa5ab090e679)
可以，非常感谢，冒昧问一下，不知道开发大大能不能把那个项目的其他平台也一并搬过来

**Comment by auqhjjqdo** [comment]
你可以使用streamlink，然后添加retry相关的参数也可以实现自动录制，但灵活性较差，具体可以查看https://streamlink.github.io/cli.html#cmdoption-retry-streams
