### ISSUE TITLE
[Bug]: 抖音是不是更新啥了？现在无法正常录制

### ISSUE THREAD

**Issue by End-Satan** [auqhjjqdo/LiveRecorder#44]
![捕获](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/4a5bf48b-8dd9-4de7-a738-1845c0c8484a)
AttributeError("'NoneType' object has no attribute 'group'")
Traceback (most recent call last):

**Comment by xjl456852** [comment]
确实是抖音无法录制
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/8008097/4a83ccc1-ee0c-492f-9eec-42628d3e459e)

**Comment by auqhjjqdo** [comment]
已更新，未完全测试是否可用，请尝试下载新版本

**Comment by 0zxcvbnm0** [comment]
![IMG_20230910_023429](https://github.com/auqhjjqdo/LiveRecorder/assets/144042768/bf0e82a1-4fb1-451b-8235-d2c5319e74a7)
这也太难用了吧，根本不行

**Comment by auqhjjqdo** [comment]
> ![IMG_20230910_023429](https://user-images.githubusercontent.com/144042768/266797401-bf0e82a1-4fb1-451b-8235-d2c5319e74a7.jpg) 这也太难用了吧，根本不行

说难用的 你是根本不看readme？

**Comment by 0zxcvbnm0** [comment]
抖音9月3号，更新了链接，之前用的好多都不能用了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月10日(周日) 上午7:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [auqhjjqdo/LiveRecorder] [Bug]: 抖音是不是更新啥了？现在无法正常录制 (Issue #44)




  
 这也太难用了吧，根本不行
  
说难用的 你是根本不看readme？

**Comment by auqhjjqdo** [comment]
> 抖音9月3号，更新了链接，之前用的好多都不能用了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年9月10日(周日) 上午7:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [auqhjjqdo/LiveRecorder] [Bug]: 抖音是不是更新啥了？现在无法正常录制 (Issue #44) 这也太难用了吧，根本不行 说难用的 你是根本不看readme？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

https://github.com/auqhjjqdo/LiveRecorder/issues/44#issuecomment-1712488208

**Comment by 0zxcvbnm0** [comment]
![IMG_20230910_085745](https://github.com/auqhjjqdo/LiveRecorder/assets/144042768/727f0582-494a-473a-a1f9-46e24514345a)
大佬，看下哪里出错了？为啥录不了？

**Comment by auqhjjqdo** [comment]
> ![IMG_20230910_085745](https://user-images.githubusercontent.com/144042768/266808624-727f0582-494a-473a-a1f9-46e24514345a.jpg) 大佬，看下哪里出错了？为啥录不了？

请把你不需要录制的主播删掉，config.sample.json里只是示例格式，youtube、twitch这些平台需要代理才能访问

**Comment by 0zxcvbnm0** [comment]
![IMG_20230910_091218](https://github.com/auqhjjqdo/LiveRecorder/assets/144042768/40051ed8-2a1a-4e96-ac12-0fb909b01562)
删了，现在exe程序打开一会儿，直接退出去了！

**Comment by auqhjjqdo** [comment]
[请先学习配置文件部分](https://github.com/auqhjjqdo/LiveRecorder#配置)
