### ISSUE TITLE
请问支持ARM架构嘛 [Enhancement]: 

### ISSUE THREAD

**Issue by Mikosxz** [auqhjjqdo/LiveRecorder#45]
### 直播平台

flextv

### 需求描述

请问支持ARM架构嘛 [Enhancement]: 

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
由于python打包的弊端，arm架构打包存在兼容性问题，你可以使用源码运行方式，理论所有支持所有平台
