### ISSUE TITLE
抖音又来大姨妈了

### ISSUE THREAD

**Issue by End-Satan** [auqhjjqdo/LiveRecorder#46]
![捕获](https://github.com/auqhjjqdo/LiveRecorder/assets/17049937/b59a2744-7522-488e-bbdd-8889268ab3b5)

**Comment by auqhjjqdo** [comment]
非程序问题，自测抖音直播录制暂无问题，请检查配置是否正确
请按照格式提交bug，不要删除issue模板
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/4542de55-d356-4045-9726-9672a2186b80)
