### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by jieli1990** [auqhjjqdo/LiveRecorder#47]
### 直播平台

花椒直播

### 需求描述

希望能增加花椒直播的录制功能

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
已经能抓到花椒直播地址，但直播间网址里的数字是否为直播间固定id需要观察，请留意一下在电脑网页端打开主播直播间时，网址中的数字是否一直保持不变，确定该参数后将更新
