### ISSUE TITLE
Twitch的cookies怎么填

### ISSUE THREAD

**Issue by justdoiting** [auqhjjqdo/LiveRecorder#48]
### 运行环境

版本号：2.23
运行平台：Windows
运行架构：x64
Python版本：3.9.10

### 配置文件

```JSON
{
      "platform": "Twitch",
      "id": "woohankyung",
      "name": "woohankyung"
      "cookies": "key=xxxxx"
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

添加cookies后直接无法启动了，把cookies改成  "cookies"："auth-token=xxxxxx"  也一样启动不了，删除之后可以录制，但是只有10秒钟的像广告的片段，一直重复，这个直播只能在登录账号的情况下观看

### 错误日志

```Text
启动不了，没有日志
```

### 错误截图（可选）

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/8c6f09ce-5eb5-4908-99b4-49cfe7d7b758)

**Comment by auqhjjqdo** [comment]
添加cookies后无法启动的原因是你的json配置文件格式错误，你的name字段后面没有添加逗号，请使用readme中的json格式化网站校验后再重新试试
v2.24版本已修复twitch广告跳过参数失效问题，请尝试新版本

**Comment by justdoiting** [comment]
加了逗号也是一样闪退的
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/4a1b10d6-9e7d-4fe6-8033-c07474b1c23b)

**Comment by auqhjjqdo** [comment]
你能不用代理直接录twitch？
另外未设置代理导致报错的bug已修复，晚些更新打包
https://github.com/auqhjjqdo/LiveRecorder/pull/50

**Comment by justdoiting** [comment]
> 你能不用代理直接录twitch？ 另外未设置代理导致报错的bug已修复，晚些更新打包 #50

可以的，我用clash开启系统代理，另外打开clash的specify protocol，python就可以实现代理了

**Comment by auqhjjqdo** [comment]
> > 你能不用代理直接录twitch？ 另外未设置代理导致报错的bug已修复，晚些更新打包 #50
> 
> 可以的，我用clash开启系统代理，另外打开clash的specify protocol，python就可以实现代理了

clash开启系统代理只对走系统代理的程序（例如浏览器）有效，由于程序并不是windows专用，所以未检测系统是否开启代理，请自行设置proxy字段未clash代理地址

**Comment by auqhjjqdo** [comment]
> 你能不用代理直接录twitch？ 另外未设置代理导致报错的bug已修复，晚些更新打包 #50

已推送新版本打包

**Comment by justdoiting** [comment]
> > > 你能不用代理直接录twitch？ 另外未设置代理导致报错的bug已修复，晚些更新打包 #50
> > 
> > 
> > 可以的，我用clash开启系统代理，另外打开clash的specify protocol，python就可以实现代理了
> 
> clash开启系统代理只对走系统代理的程序（例如浏览器）有效，由于程序并不是windows专用，所以未检测系统是否开启代理，请自行设置proxy字段为clash代理地址

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/7ffc0c03-f084-4e5e-9c23-c0e47ce403bd)
不需要设置代理的

**Comment by justdoiting** [comment]
2.25已修复，可以close了
