### ISSUE TITLE
[Bug]: 抖音是不是录制的主播过多会漏-

### ISSUE THREAD

**Issue by End-Satan** [auqhjjqdo/LiveRecorder#49]
### 运行环境

版本号：2.23
运行平台：windows
运行架构：exe
Python版本：python3.11

### 配置文件

```JSON
{
      "platform": "Douyin",
      "id": "320175369511",
      "name": "卜斯斯"
    },
    {
      "platform": "Douyin",
      "id": "69722554767",
      "name": "坂田猫猫"
    },
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

最近很多主播都没有录到，明明在直播但是一直没录。不知道什么情况。就抖音这样，斗鱼正常

### 错误日志

```Text
无
```

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/f021c2cd-ed46-4fc2-950a-068d7fc9aea8)
随机找了两个正在直播的直播间能正常同时录制，由于抖音的逻辑刚更新还不清楚status参数分别有哪些值，不排除存在其他直播状态但没录制的情况，如果你在主播直播后重启程序依然没有录制那就可能开播状态判断有其他情况需要更新

**Comment by 0zxcvbnm0** [comment]
能否告诉我怎么使用，压缩包解压，里面就俩文件json文件也重命名了，，直接运行程序，里面显示“服务器拒绝连接”,……检测直播失败。我录的抖音的

**Comment by auqhjjqdo** [comment]
> 能否告诉我怎么使用，压缩包解压，里面就俩文件json文件也重命名了，，直接运行程序，里面显示“服务器拒绝连接”,……检测直播失败。我录的抖音的

请不要在别人的issue提问题
