### ISSUE TITLE
[Enhancement]: pandalive 录制

### ISSUE THREAD

**Issue by tzy002485** [auqhjjqdo/LiveRecorder#51]
### 直播平台

pandalive

### 需求描述

平台api更新后一直不能录制了

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
已更新修复，请尝试v2.26版本

**Comment by yukminnie** [comment]
> 已更新修复，请尝试v2.26版本

老哥, 这个你平时会录吗, 我录制了几天, 号被ban 了. 💔

**Comment by auqhjjqdo** [comment]
> > 已更新修复，请尝试v2.26版本
> 
> 老哥, 这个你平时会录吗, 我录制了几天, 号被ban 了. 💔

pandalive我自己平时不录，是有人提需求加的平台，号被ban那就是平台有风控，这种无解
