### ISSUE TITLE
[Bug]: macOS运行不了

### ISSUE THREAD

**Issue by popularhoney** [auqhjjqdo/LiveRecorder#52]
### 运行环境

版本号：2.26
运行平台：macOS
运行架构：
Python版本：3

### 配置文件

```JSON
{
  "proxy": null,
  "output": "output",
  "user": [
    {
      "platform": "Douyin",
      "id": "532339968826"
    },
    {
      "platform": "Douyin",
      "id": "396414978034"
    },
    {
      "platform": "Douyin",
      "id": "604842626817"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

运行终端显示错误
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[52956] Failed to execute script 'live_recorder' due to unhandled exception!

### 错误日志

```Text
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[52956] Failed to execute script 'live_recorder' due to unhandled exception!
```

### 错误截图（可选）

<img width="552" alt="图片" src="https://github.com/auqhjjqdo/LiveRecorder/assets/147444889/9457afc7-ca88-4625-a408-445b9fbef9f7">

**Comment by auqhjjqdo** [comment]
请确认配置文件已重命名为`config.json`并置于程序相同运行目录下

**Comment by popularhoney** [comment]
<img width="292" alt="图片" src="https://github.com/auqhjjqdo/LiveRecorder/assets/147444889/b725293c-8ce7-45c5-b6a5-2a5b63368fdf">
已经重命名了 所以才觉得奇怪

**Comment by popularhoney** [comment]
我可以拥有你的联系方式吗 我纯小白🥹

**Comment by auqhjjqdo** [comment]
本程序在非常用平台部署需要一定经验，你可以选择同类软件
如果你只需要抖音录制，你可以尝试https://github.com/ihmily/DouyinLiveRecorder

**Comment by popularhoney** [comment]
好的 谢谢

**Comment by popularhoney** [comment]
好难啊 您推荐的这个也没有mac 哭了

**Comment by auqhjjqdo** [comment]
> 好难啊 您推荐的这个也没有mac 哭了

换windows电脑吧，macos除了生产力好用别的都挺麻烦

**Comment by zihaoxingstudy1** [comment]
> macos我没有设备做测试，打包是github actions自动运行的，你尝试一下在python环境下用源码运行

请问可以录制抖音直播的互动弹幕和评论吗

**Comment by auqhjjqdo** [comment]
> > macos我没有设备做测试，打包是github actions自动运行的，你尝试一下在python环境下用源码运行
> 
> 请问可以录制抖音直播的互动弹幕和评论吗

https://github.com/auqhjjqdo/LiveRecorder/issues/34

**Comment by ysn4444** [comment]
远程计算机拒绝网络链接，直播检测错误要怎么解决？

**Comment by auqhjjqdo** [comment]
> 远程计算机拒绝网络链接，直播检测错误要怎么解决？

请不要在别人的issue提问
