### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 786518082** [auqhjjqdo/LiveRecorder#53]
### 运行环境

版本号：2.26
运行平台：windows
运行架构：exe
Python版本：python3.11

### 配置文件

```JSON
{
      "platform": "Afreeca",
      "id": "rkdmf2179",
      "name": "루시아",
      "interval": 10,
      "format": "mp4",
    },
    {
      "platform": "Pandalive",
      "id": "syxx12",
      "name": "syxx12",
      "interval": 10,
      "format": "mp4",
    }
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

请问大佬，pandatv要怎么录制啊？我运行后显示检测直播状态但是并没有录制，是要登陆账号密码吗，json里具体要怎么写呢。还有afreeca的19+房间，显示没有检测到直播源。求指导

### 错误日志

```Text
无
```

**Comment by auqhjjqdo** [comment]
示例里的cookies只适用于bilibili，不同平台的cookies不一样，怎么获取一个网站的cookies谷歌上一大堆，按示例的格式填写即可，注意cookies是有有效期的

**Comment by 786518082** [comment]
好的谢谢
