### ISSUE TITLE
请问可以支持instagram平台的直播录制嘛？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [auqhjjqdo/LiveRecorder#54]
### 直播平台

instagram

### 需求描述

请问可以支持instagram平台的直播录制嘛？

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
我没找到Instagram的直播网站，能方便发一个直播链接吗

**Comment by zihaoxingstudy1** [comment]
instagram手机软件里面有直播功能，我还没在电脑网站上看过
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年11月2日 19:11
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [auqhjjqdo/LiveRecorder] 请问可以支持instagram平台的直播录制嘛？ (Issue #54)
        
      
    
  

我没找到Instagram的直播网站，能方便发一个直播链接吗

**Comment by auqhjjqdo** [comment]
手机软件里才有的话，估计支持比较困难，一般手机客户端会有很多加密，如果有其他录制ins直播的项目可以发一下

**Comment by lhs55502002** [comment]
同希望增加IG直播监控。之前我用的是这个https://github.com/evanc577/download-iglive，但是现在这个经常下不了了，只能下一些片段，无法自动合并。

https://www.youtube.com/watch?v=2Wyd-vWEZX8，这个是找谁正在IG直播的方法，需要两个账号。找到正在直播的账号就可以用电脑网页搜索这个人进行测试了。
