### ISSUE TITLE
[Enhancement]: Bigo TV的pr（未测试）

### ISSUE THREAD

**Issue by justdoiting** [auqhjjqdo/LiveRecorder#56]
### 直播平台

bigo.tv

### 需求描述

别人blog看到的经验分享，实现出处 https://blog.gocos.cn/archives/248.html

import requests
import time
import os
import threading
import random
import datetime

class Bigo:
    def __init__(self, rid):
        self.rid = rid
        self.flag = False
        self.run = False

    def get_real_url(self):
        with requests.Session() as s:
            url = f'https://ta.bigo.tv/official_website/studio/getInternalStudioInfo'
            res = s.post(url, data={'siteId': self.rid}).json()
            hls_src = res['data']['hls_src']
            play_url = hls_src if hls_src else None
            return play_url

    def checkLive(self):
        try:
            u = self.get_real_url()
            if u:
                print('正在直播！',u)
                self.flag = True
            else:
                print('未直播')
                self.flag = False
                time.sleep(random.randint(10,30))
        except Exception as e:
            print('Exception：', e)
            self.flag = False

    def ffmpegDown(self):
        url = self.get_real_url()
        print('直播源：',url)
        filename = datetime.datetime.today()
        filename = filename.strftime('%Y%m%d%H%M%S')
        filename = filename + '.mp4'
        print(filename)
        file_path = "./"
        print('ffmpeg -i {} -c copy {}'.format(url, os.path.join(file_path,filename)))
        os.system('ffmpeg -i {} -c copy {}'.format(url, os.path.join(file_path,filename)))

    def recording(self):
        while True:
            print("-------recoding-------")
            time.sleep(5)
            if self.flag == True and self.run == False:
                print("---开始录制")
                self.ffmpegDown()
                self.run = True
            elif self.flag == True and self.run == True:
                print("---正在录制")
            else:
                print('---未直播')
                self.run = False

if __name__ == '__main__':
    r = input('输入bigo直播房间号：\n')
    site = Bigo(r)
    change = threading.Thread(target=site.checkLive)
    ffm = threading.Thread(target=site.recording)
    # 开始运行程序
    change.start()
    ffm.start()

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
感谢分享经验，已在v2.27版本中新增Bigotv的直播录制，请测试是否正常录制

**Comment by justdoiting** [comment]
> 感谢分享经验，已在v2.27版本中新增Bigotv的直播录制，请测试是否正常录制

录是可以录，但是画质和分辨率都非常差，和浏览器插件抓源的不一样
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/83c8f70e-8a4b-40ee-87c9-c2f9083e7e8b)

**Comment by auqhjjqdo** [comment]
> > 感谢分享经验，已在v2.27版本中新增Bigotv的直播录制，请测试是否正常录制
> 
> 录是可以录，但是画质和分辨率都非常差，和浏览器插件抓源的不一样 ![image](https://user-images.githubusercontent.com/109136320/280017588-83c8f70e-8a4b-40ee-87c9-c2f9083e7e8b.png)

我是读的网页端接口返回的直播地址，这个地址只有一个，我也没看到bigolive有清晰度的选项，你用的哪个浏览器插件抓的

**Comment by justdoiting** [comment]
> > > 感谢分享经验，已在v2.27版本中新增Bigotv的直播录制，请测试是否正常录制
> > 
> > 
> > 录是可以录，但是画质和分辨率都非常差，和浏览器插件抓源的不一样 ![image](https://user-images.githubusercontent.com/109136320/280017588-83c8f70e-8a4b-40ee-87c9-c2f9083e7e8b.png)
> 
> 我是读的网页端接口返回的直播地址，这个地址只有一个，我也没看到bigolive有清晰度的选项，你用的哪个浏览器插件抓的

猫抓

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/25fe60f8-5934-4a16-9059-55551ae8b8ea)
我这边随机找了直播间测试猫抓的网址和接口返回的是一致的，分辨率问题暂时无解

**Comment by justdoiting** [comment]
> ![image](https://user-images.githubusercontent.com/84632728/280435937-25fe60f8-5934-4a16-9059-55551ae8b8ea.png) 我这边随机找了直播间测试猫抓的网址和接口返回的是一致的，分辨率问题暂时无解

下载器的问题，ffmpeg正常，改调用ffmpeg吧，或者看看streamlink是不是有隐藏参数
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/8904113b-3a78-454d-b236-56baadff541e)

**Comment by auqhjjqdo** [comment]
原理上不可能是下载器的问题，直播流的地址始终是固定的，ffmpeg只是转码，streamlink也只是下载作用
我这边改成你发的这个主播id直接录制，然后用potplayer打开看到的画质是最清晰的版本，无法复现你那边出现的低清晰度的情况
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/f2a82c75-3b19-4475-9a64-76b23a1bdcaf)
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/7bfd01fb-0722-46ba-8578-13ab33b1954b)

**Comment by auqhjjqdo** [comment]
请检查输出日志中提取到的直播流地址使用potplayer打开url是不是正常

**Comment by justdoiting** [comment]
> 请检查输出日志中提取到的直播流地址使用potplayer打开url是不是正常

直接把log里面的URL贴到potplayer里面播放也是低分辨率的
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/caa1c262-66ae-4745-b838-c728b8fa9c08)

**Comment by auqhjjqdo** [comment]
> > 请检查输出日志中提取到的直播流地址使用potplayer打开url是不是正常
> 
> 直接把log里面的URL贴到potplayer里面播放也是低分辨率的 ![image](https://user-images.githubusercontent.com/109136320/280464934-caa1c262-66ae-4745-b838-c728b8fa9c08.png)

你那边录制文件右键属性看看分辨率是多少
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/1da3c545-aa0e-4bc7-896d-8740de55f0e9)

**Comment by justdoiting** [comment]
> > > 请检查输出日志中提取到的直播流地址使用potplayer打开url是不是正常
> > 
> > 
> > 直接把log里面的URL贴到potplayer里面播放也是低分辨率的 ![image](https://user-images.githubusercontent.com/109136320/280464934-caa1c262-66ae-4745-b838-c728b8fa9c08.png)
> 
> 你那边录制文件右键属性看看分辨率是多少 ![image](https://user-images.githubusercontent.com/84632728/280465459-1da3c545-aa0e-4bc7-896d-8740de55f0e9.png)

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/8bec2e61-c8f3-4ac4-8ed9-def1dc5fdb8d)
