### ISSUE TITLE
format配置内容未生效

### ISSUE THREAD

**Issue by tothk** [auqhjjqdo/LiveRecorder#60]
### 运行环境

版本号：v2.27
运行平台：

版本	Windows 10 企业版 LTSC
版本号	21H2
安装日期	‎2023/‎8/‎23
操作系统内部版本	19044.3086

运行架构：x86_64
Python版本：Python 3.10.11
ffmpeg版本：
ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers

### 配置文件

```JSON
{
  "output": "output",
  "user": [
    {
      "platform": "Douyu",
      "id": "6829849",
      "name": "6657", 
      "format": "mp4",
      "headers": {
        "Referer": "https://www.douyu.com/"
      }, 
      "cookies": ""
    }
  ]
}
```

### 错误描述

在如上的配置文件中，"format": "mp4"该行配置未能实现如期效果，录制输出的文件任然为最初的flv格式

### 错误日志

```Text
[2023-11-08 19:33:40][INFO][__main__][start:47][Douyu][6657]正在检测直播状态
[2023-11-08 19:33:42][INFO][__main__][run_record:132][Douyu][6657]开始录制：[2023.11.08 19.33.42][Douyu][6657]【直播】2023反恐精英亚洲邀请赛.flv
[2023-11-08 19:33:42][INFO][__main__][stream_writer:144][Douyu][6657]获取到直播流链接：[2023.11.08 19.33.42][Douyu][6657]【直播】2023反恐精英亚洲邀请赛.flv
https://tc-tct.douyucdn2.cn/dyliveflv1/6829849rvRdF9Fss.flv?wsAuth=b0f8d65f595dd48dfd1c54cdaec4e01d&token=web-h5-0-6829849-5788c6a6f832f98ea5eb43a6f98725b60c2069ae1a4d4e81&logo=0&expire=0&did=473098839df04aafaad62b7a99bc58ff&pt=2&st=0&sid=369453165&mcid2=0&origin=tct&mix=0&isp=
[2023-11-08 19:33:43][INFO][__main__][stream_writer:150][Douyu][6657]正在录制：[2023.11.08 19.33.42][Douyu][6657]【直播】2023反恐精英亚洲邀请赛.flv
```

**Comment by tothk** [comment]
> 录制过程中是直播流的原始文件格式防止网络原因导致中断，主播下播后或使用ctrl+c中断录制后会进行封装

下播后这个我还没测试到，但是ctrl+c中断录制这个我在提交issues之前操作过几次，并没有进行封装，很久之后输出文件夹还是只有原始的flv格式，因为我是在nas上录制的，在停止录制后不会动源录制文件，只是复制到当前电脑手动重新封装

**Comment by auqhjjqdo** [comment]
中断录制不能连续按ctrl+c，只能按一次之后会提示中断录制等待ffmpeg封装，多次按会直接中断封装

**Comment by tothk** [comment]
> 中断录制不能连续按ctrl+c，只能按一次之后会提示中断录制等待ffmpeg封装，多次按会直接中断封装

好的，我试试

**Comment by tothk** [comment]
> 中断录制不能连续按ctrl+c，只能按一次之后会提示中断录制等待ffmpeg封装，多次按会直接中断封装

测试成功了，已自动封装成mp4
