### ISSUE TITLE
感谢脚本，提交个BUG，就是文件名太长的话会报错

### ISSUE THREAD

**Issue by danchuns** [auqhjjqdo/LiveRecorder#64]
### 运行环境

版本号：null
运行平台：linux
运行架构：null
Python版本：3.11

### 配置文件

```JSON
null
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

直播完发现录制没出文件，看了一下日志录制没问题，但是到最后的时候出现了“OSError: [Errno 36] File name too long”的错误，网上搜了一下，大概就是文件名过长的问题了。不熟悉python，不知道是不是版本的原因吧，后面找了个代码。然后把filename那改成了"filename = filename.encode('utf-8')[:255].decode('utf-8', 'ignore')"，不知道有没有问题。

### 错误日志

```Text
OSError: [Errno 36] File name too long: 'output/{一段很长的标题，不方便放出}'
```

**Comment by auqhjjqdo** [comment]
已发布v2.29版本限制直播标题长度，未测试对文件名过长报错是否有效

**Comment by danchuns** [comment]
> 已发布v2.29版本限制直播标题长度，未测试对文件名过长报错是否有效

好像还是不行，我放个测试标题吧。
◯本本本本本本本！【本本コ本本本ABCD】本本本本の本本めで本本を本本本本♡本本に本に本本本本本本本本本本本本本本本本本本本本本本本本本♡【AC200_本本本】

**Comment by auqhjjqdo** [comment]
刚发现你的运行平台是在linux，我在windows一直没文件名过长的报错，已经将标题的长度截断到50了，用你的测试标题试了下没问题了，但是因为截断所以标题后半段不完整需要自己改文件名，v2.29已更新请重新下载
