### ISSUE TITLE
B站无法连接

### ISSUE THREAD

**Issue by justdoiting** [auqhjjqdo/LiveRecorder#67]
### 运行环境

版本号：2.29
运行平台：Windows
运行架构：x64
Python版本：3.9.10

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:7890",
  "user": [
    {
      "platform": "Bilibili",
      "id": "394518",
      "name": "仙若"
    },
	{
      "platform": "Bilibili",
      "id": "999",
      "name": "梦泪"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

B站无法连接，未测试加入cookie的情况

### 错误日志

```Text
[2023-12-07 15:07:26][ERROR][__main__][start:58][Bilibili][梦泪]直播检测错误
PluginError('Unable to open URL: https://live.bilibili.com/999 (400 Client Error: Bad Request for url: https://live.bilibili.com/999)')
Traceback (most recent call last):

  File "live_recorder.py", line 467, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 186, in run

  File "streamlink\session.py", line 625, in streams

  File "streamlink\plugin\plugin.py", line 375, in streams

  File "C:\Users\dozen\AppData\Local\Temp\_MEI96002\streamlink\plugins\bilibili.py", line 47, in _get_streams
    data = self.session.http.get(
           │    │       │    └ <function Session.get at 0x000002299268D360>
           │    │       └ <streamlink.plugin.api.http_session.HTTPSession object at 0x0000022992D0ACE0>
           │    └ <streamlink.session.Streamlink object at 0x0000022992CA45E0>
           └ <streamlink.plugins.bilibili.Bilibili object at 0x0000022993D3FC10>

  File "requests\sessions.py", line 602, in get

  File "streamlink\plugin\api\http_session.py", line 190, in request

streamlink.exceptions.PluginError: Unable to open URL: https://live.bilibili.com/999 (400 Client Error: Bad Request for url: https://live.bilibili.com/999)
```

### 错误截图（可选）

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/a407b5fe-7dfb-4584-8c6a-d3c6ef35e980)

**Comment by auqhjjqdo** [comment]
https://github.com/auqhjjqdo/LiveRecorder#哔哩哔哩的房间号
这个直播间的链接是短号，`https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=999`这个链接可以查到原始直播间id为4245963

**Comment by justdoiting** [comment]
> [https://github.com/auqhjjqdo/LiveRecorder#哔哩哔哩的房间号](https://github.com/auqhjjqdo/LiveRecorder#%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%9A%84%E6%88%BF%E9%97%B4%E5%8F%B7) 这个直播间的链接是短号，`https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=999`这个链接可以查到原始直播间id为4245963

OK，我看直播间画面里面写的999，原来点击头像才显示真正的房间号

**Comment by justdoiting** [comment]
> [https://github.com/auqhjjqdo/LiveRecorder#哔哩哔哩的房间号](https://github.com/auqhjjqdo/LiveRecorder#%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%9A%84%E6%88%BF%E9%97%B4%E5%8F%B7) 这个直播间的链接是短号，`https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=999`这个链接可以查到原始直播间id为4245963

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/325020e9-25b0-4c0c-a5c3-b0bd963d2dae)
真实房间号也不行

**Comment by justdoiting** [comment]
在网页使用真实房间号打开也会直接跳转到短号

**Comment by auqhjjqdo** [comment]
看了下上有streamlink，有相关的issue：
https://github.com/streamlink/streamlink/issues/5692
https://github.com/streamlink/streamlink/issues/5700
相关修复的pr还没有发布到正式版release，因此本程序也会受到上游影响
B站疑似限制了未登录用户的直播清晰度，未来可能所有录制都需要添加cookie
叔叔我啊......

**Comment by auqhjjqdo** [comment]
v2.30已更新依赖库streamlink v6.5.0版本，bilibili录制报错问题已解决，但只能录制到较低清晰度的直播，仍需要上游streamlink更新

**Comment by justdoiting** [comment]
> v2.30已更新依赖库streamlink v6.5.0版本，bilibili录制报错问题已解决，但只能录制到较低清晰度的直播，仍需要上游streamlink更新

上游不是说没有手机号搞不了B站账号

**Comment by auqhjjqdo** [comment]
> > v2.30已更新依赖库streamlink v6.5.0版本，bilibili录制报错问题已解决，但只能录制到较低清晰度的直播，仍需要上游streamlink更新
> 
> 上游不是说没有手机号搞不了B站账号

要B站账号的目的是为了拿到cookies，上游没有将cookies写入请求中

**Comment by auqhjjqdo** [comment]
已经更新了哔哩哔哩的直播流获取，现在需要填写cookies才能录制到原画画质
