### ISSUE TITLE
请问能增加一个录制pixivsketch的直播的功能吗？

### ISSUE THREAD

**Issue by Looper0o** [auqhjjqdo/LiveRecorder#69]
### 直播平台

pixivsketch

### 需求描述

https://sketch.pixiv.net/   请问可以增加一个pixivsketch直播视频录制功能吗？ 感谢^^

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
已尝试新增Pixiv Sketch直播录制，请下载v2.30版本测试是否可用

**Comment by chenduxiu0o** [comment]
> 已尝试是否新增Pixiv Sketch直播录制，请下载v2.30版本测试可用

太感谢了，但是我刚刚测试了，用不了。您也可以试试。LiveRecorder 打开后直接是闪退 ，我又尝试了把Pixivsketch的部分从config.json文件里删除这个软件才可以正常运行。

**Comment by auqhjjqdo** [comment]
> > 已尝试是否新增Pixiv Sketch直播录制，请下载v2.30版本测试可用
> 
> 太感谢了，但是我刚刚测试了，用不了。您也可以试试。LiveRecorder 打开后直接是闪退 ，我又尝试了把Pixivsketch的部分从config.json文件里删除这个软件才可以正常运行。

打开后直接闪退大概率是config.json文件并非json格式，建议去readme中的json校验网址校验一下

**Comment by Looper0o** [comment]
刚刚试了不闪退了但是我输入ID 和名字后就一直这样 
![AAA](https://github.com/auqhjjqdo/LiveRecorder/assets/73021797/1b914948-e78c-4c3c-afe7-331634881965)

这个人这个时候是在直播的 并不会自动开始录制视频

**Comment by auqhjjqdo** [comment]
> 刚刚试了不闪退了但是我输入ID 和名字后就一直这样 ![AAA](https://private-user-images.githubusercontent.com/73021797/292625004-1b914948-e78c-4c3c-afe7-331634881965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzk5MzYsIm5iZiI6MTcwMzMzOTYzNiwicGF0aCI6Ii83MzAyMTc5Ny8yOTI2MjUwMDQtMWI5MTQ5NDgtZTc4Yy00YzNjLWFmZTctMzMxNjM0ODgxOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEzNTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NTg0Zjc1NmY2NzM4MDk1ZWVhNzBkNmUxOGQ1ZmY4OGNmNWJjMjljZGQ4NDA5ZmE5NTVkYjFkYTI2NzcyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9uIZOOdLPGHtjiWj1BwXWriPgV3fcvx-TSUYufIFmXs)
> 
> 这个人这个时候是在直播的 并不会自动开始录制视频

pixiv sketch部分直播间是未成年禁止观看的，所以需要登录才能录制，请按照示例将cookies写进config.json

**Comment by Looper0o** [comment]
录制视频所需的这个网站的登录后的cookies具体在哪找？可以教一下吗？谢谢

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/de7f965f-905f-437f-bf90-f4811f9c16fa)

**Comment by Looper0o** [comment]
谢谢大佬，这下真的有用了^^b

**Comment by auqhjjqdo** [comment]
注意cookies是有有效期的，可能一段时间后就录制不了需要更新成新的cookies

**Comment by Looper0o** [comment]
好的，谢谢
