### ISSUE TITLE
直播检测请求未知错误，是我的问题吗

### ISSUE THREAD

**Issue by lhs55502002** [auqhjjqdo/LiveRecorder#7]
<img width="858" alt="屏幕截图 2023-04-20 213137" src="https://user-images.githubusercontent.com/62332619/233382289-a9fa334a-0f66-4238-bf90-d5528444886e.png">
<img width="860" alt="屏幕截图 2023-04-20 213106" src="https://user-images.githubusercontent.com/62332619/233382710-c629f37d-968d-42d2-819e-2a47e0f88025.png">

主播首页：https://www.youtube.com/@CuteKR

**Comment by auqhjjqdo** [comment]
软件每次出现网络丢包导致的请求失败都会输出错误，所以检查你自己的代理是不是网络不稳定
你这个网络错误密集程度取决于你配置文件的检测时间间隔，超过间隔时间才报错说明中间是有正常请求成功的只是没输出而已
要确认是不是真的能运行，你可以临时在配置文件加一个正在直播的频道，直接运行就开始录制就说明直播检测请求是成功的，只是丢包比较多所以报错比较多
