### ISSUE TITLE
Add the option to disable "output"

### ISSUE THREAD

**Issue by Patraskon** [auqhjjqdo/LiveRecorder#72]
### 直播平台

-

### 需求描述

Add the option to disable "output"

**Comment by auqhjjqdo** [comment]
output选项的含义是自定义直播录制的输出目录，这是一个非必填字段，当未填写该字段时默认保存在运行目录

**Comment by Patraskon** [comment]
Is it possible to make it so that it does not save the stream, but simply displays a link to m3u8 in the terminal?

**Comment by auqhjjqdo** [comment]
因为本程序使用轮询机制检测直播是否开播，在开始录制直播后才会停止检测，若未录制则会持续检测，因此会重复输出m3u8链接
如果你需要获取链接的直播平台是[streamlink支持的平台](https://streamlink.github.io/plugins.html)，你可以使用streamlink的`-j`参数，例如：`streamlink -j https://www.twitch.tv/lolworldchampionship best`
