### ISSUE TITLE
定时停止录制任务

### ISSUE THREAD

**Issue by KKCAT-77** [auqhjjqdo/LiveRecorder#73]
### 直播平台

1

### 需求描述

ctrl+c可手动停止录制并转码，可以增加一个定时在cmd窗口执行ctrl+c的功能吗，感谢大佬！

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
定时任务请使用系统自带功能，本程序仅做直播录制相关功能
windows系统：任务计划程序+taskkill命令
linux系统：crontab+kill命令
