### ISSUE TITLE
Pixivsketch现在又录不了了

### ISSUE THREAD

**Issue by Looper0o** [auqhjjqdo/LiveRecorder#74]
### 运行环境

版本号：LiveRecorder2.30
运行平台：
运行架构：
Python版本：

### 配置文件

```JSON
{
	"output": "output",
	"user": [{
		"platform": "Pixivsketch",
		"id": "@blue_gk",
		"name": "@blue_gk",
		"": "_sketch_session=8bC1rxN3IUZrdlKWB7h2tb6JqXve7F5C0a2qShdCoiND7g5bsPriR0TFQQT5pIotJMjbzA7Dn42ALj9Yk2n5L6KSZVPO4psYXMPMcTj2NeYH6t2qskf3X%2FYV13oeDmCcSRA4HU8iXEqLf80hQMLOkOaFOByvPpG1tHmaopOwOYT%2Bzdb5rJGXPzfY2nTyHburZAhXLsjz1fTze21%2Bd%2By3GZKqUrDB8t2KfKmf0bw37wAiIYZoISNwVQjpNMmH93eUqWb798DavzIpqjDzzLOo8oLq70KW--97oMLlYgeKTddh0v--XPOCnTEoOMzXZmc%2Fm4ecvw%3D%3D"
	}]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

你好，Pixivsketch又录不了了，我更新了_sketch_session=
目前是报错，直播检测错误

### 错误日志

```Text
已上传
```

### 错误截图（可选）

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/73021797/49e51e6a-3b5f-48f8-be91-5152d7611b4f)
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/73021797/67a975ca-2753-4e8b-ae56-236655aef933)

**Comment by auqhjjqdo** [comment]
请不要随意删除cookies这些键值，并使用readme中的json格式化校验配置文件是否正确

**Comment by Looper0o** [comment]
有用readme中的Json格式化校检配置文件是否正确，还是没用，后面我重新安装了好几次了， 一样录不了，不信你试试。

**Comment by auqhjjqdo** [comment]
> 有用readme中的Json格式化校检配置文件是否正确，还是没用，后面我重新安装了好几次了， 一样录不了，不信你试试。

你的格式是正确的，但原本示例文件中的cookies这个字符被你删了，就算程序没有问题你也录不了必须登录才能看的直播
另外程序的问题已经找到，稍后更新

**Comment by Looper0o** [comment]
好的，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月27日 10:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [auqhjjqdo/LiveRecorder] Pixivsketch现在又录不了了 (Issue #74) |

有用readme中的Json格式化校检配置文件是否正确，还是没用，后面我重新安装了好几次了， 一样录不了，不信你试试。

你的格式是正确的，但原本示例文件中的cookies这个字符被你删了，就算程序没有问题你也录不了必须登录才能看的直播
另外程序的问题已经找到，稍后更新

**Comment by Looper0o** [comment]
示例文件中的cookies这个字符被我删了  因为上传的时候 我看介绍那里说不能出现这个字样，所以就删掉这个了，不好意思

**Comment by auqhjjqdo** [comment]
v2.31已更新修复Pixivsketch录制报错

**Comment by Looper0o** [comment]
谢谢，辛苦了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月27日 13:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [auqhjjqdo/LiveRecorder] Pixivsketch现在又录不了了 (Issue #74) |

v2.31已更新修复Pixivsketch录制报错
