### ISSUE TITLE
抖音录制时报报错

### ISSUE THREAD

**Issue by zxp3721** [auqhjjqdo/LiveRecorder#76]
### 运行环境

版本号：v2.30
运行平台：debian11
运行架构：x64
Python版本：Python 3.9.2

### 配置文件

```JSON
{
  "output": "output",
  "user": [
    {
      "platform": "Douyin",
      "id": "851327597359",
      "name": "静雅"
    }
  ]
}
```

### 复现步骤（可选）

1.通过git安装最新版源码
2.config.json写入配置文件
3.运行live_recorder.py报错
...

### 错误描述

运行后出现 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 错误，config.json 使用的是uft8编码，校验后证明是正确的json，不知道问题出在哪

### 错误日志

```Text
root@debian:~/LiveRecorder# python3 live_recorder.py
2023-12-26 13:33:13.572 | INFO     | __main__:start:47 - [Douyin][静雅]正在检测直播状态
2023-12-26 13:33:13.835 | ERROR    | __main__:start:58 - [Douyin][静雅]直播检测错误
JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):

  File "/root/LiveRecorder/live_recorder.py", line 483, in <module>
    asyncio.run(run())
    │       │   └ <function run at 0x7f02a32cbf70>
    │       └ <function run at 0x7f02a32e3550>
    └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>

  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object run at 0x7f02a0ca0d40>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f02a2bbe940>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f02a2bbe8b0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f02a2bc1430>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f02a2c2e3a0>
    └ <Handle <TaskStepMethWrapper object at 0x7f02a034ea00>()>
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f02a034ea00>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f02a034ea00>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f02a034ea00>()>

> File "/root/LiveRecorder/live_recorder.py", line 50, in start
    await self.run()
          │    └ <function Douyin.run at 0x7f02a0c51ee0>
          └ <__main__.Douyin object at 0x7f02a0c53550>

  File "/root/LiveRecorder/live_recorder.py", line 259, in run
    response = (await self.request(
                      │    └ <function LiveRecoder.request at 0x7f02a0c51820>
                      └ <__main__.Douyin object at 0x7f02a0c53550>

  File "/usr/local/lib/python3.9/dist-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           │       │     │    │          └ {}
           │       │     │    └ <property object at 0x7f02a2474c20>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x7f02a2b10b80>
           └ <module 'json' from '/usr/lib/python3.9/json/__init__.py'>

  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x7f02a2b10550>
           └ <json.decoder.JSONDecoder object at 0x7f02a32e9e80>
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x7f02a2b7b4b0>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x7f02a2b105e0>
               └ <json.decoder.JSONDecoder object at 0x7f02a32e9e80>
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### 错误截图（可选）

![2023-12-26_133437](https://github.com/auqhjjqdo/LiveRecorder/assets/9151620/e32f9da7-4a1e-4233-8f5a-c3d3e9f3013e)

**Comment by AvrilL161** [comment]
I have the same problem.
if you add an ID from letters (for example "shentaototo") then everything will work fine.
but if you add an ID from numbers (for example "476616721907") there will be an error.

**Comment by KKCAT-77** [comment]
手动输入，不要直接复制

**Comment by AvrilL161** [comment]
> 手动输入，不要直接复制

please explain in more detail.

For example https://live.douyin.com/352593585494

this does not work
{
  "output": "vid",
  "user": [
    {
      "platform": "Douyin",
      "id": "352593585494",
      "name": "tst"
    }
  ]
}

this does not work
{
  "output": "vid",
  "user": [
    {
      "platform": "Douyin",
      "id": "71548300543",
      "name": "tst"
    }
  ]
}

but if the ID is made up of letters, it works
{
  "output": "vid",
  "user": [
    {
      "platform": "Douyin",
      "id": "gezi6668888",
      "name": "tst"
    }
  ]
}

**Comment by auqhjjqdo** [comment]
v2.31已修复抖音直播录制报错

**Comment by xbclub** [comment]
> v2.31已修复抖音直播录制报错

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/33245941/6a139268-01c7-4d2e-b6e8-67db115190be)
v2.31 照常报错

**Comment by auqhjjqdo** [comment]
> > v2.31已修复抖音直播录制报错
> 
> ![image](https://private-user-images.githubusercontent.com/33245941/293322624-6a139268-01c7-4d2e-b6e8-67db115190be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA5MTMsIm5iZiI6MTcwMzkwMDYxMywicGF0aCI6Ii8zMzI0NTk0MS8yOTMzMjI2MjQtNmExMzkyNjgtMDFjNy00ZDJlLWI2ZTgtNjdkYjExNTE5MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWNhZDdhZTU2OTE2YzgyNjAzMzM0MjIxMTNhZDc0YTExOTA2M2RhYzEzOGIwNGE4YjA3OGFkOWQ0ODJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ULDXgwz-lSltB9SZ7DzXyKpiRd0nKSTsBIwDJaIx0s) v2.31 照常报错

我这边测试录制没问题，你的直播间id写对了吗，是一串数字那个id

**Comment by xbclub** [comment]
> > > v2.31已修复抖音直播录制报错
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/33245941/293322624-6a139268-01c7-4d2e-b6e8-67db115190be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA5MTMsIm5iZiI6MTcwMzkwMDYxMywicGF0aCI6Ii8zMzI0NTk0MS8yOTMzMjI2MjQtNmExMzkyNjgtMDFjNy00ZDJlLWI2ZTgtNjdkYjExNTE5MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWNhZDdhZTU2OTE2YzgyNjAzMzM0MjIxMTNhZDc0YTExOTA2M2RhYzEzOGIwNGE4YjA3OGFkOWQ0ODJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ULDXgwz-lSltB9SZ7DzXyKpiRd0nKSTsBIwDJaIx0s) v2.31 照常报错
> 
> 我这边测试录制没问题，你的直播间id写对了吗，是一串数字那个id

```json
{
  "user": [
    {
      "platform": "Douyin",
      "id": "965952812349",
      "name": "ax-1001",
      "output": "/data/lubo/ax-1001"
    }
  ]
}
```

**Comment by auqhjjqdo** [comment]
> > > > v2.31已修复抖音直播录制报错
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/33245941/293322624-6a139268-01c7-4d2e-b6e8-67db115190be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA5MTMsIm5iZiI6MTcwMzkwMDYxMywicGF0aCI6Ii8zMzI0NTk0MS8yOTMzMjI2MjQtNmExMzkyNjgtMDFjNy00ZDJlLWI2ZTgtNjdkYjExNTE5MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWNhZDdhZTU2OTE2YzgyNjAzMzM0MjIxMTNhZDc0YTExOTA2M2RhYzEzOGIwNGE4YjA3OGFkOWQ0ODJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ULDXgwz-lSltB9SZ7DzXyKpiRd0nKSTsBIwDJaIx0s) v2.31 照常报错
> > 
> > 
> > 我这边测试录制没问题，你的直播间id写对了吗，是一串数字那个id
> 
> ```json
> {
>   "user": [
>     {
>       "platform": "Douyin",
>       "id": "965952812349",
>       "name": "ax-1001",
>       "output": "/data/lubo/ax-1001"
>     }
>   ]
> }
> ```

macos系统没测试不知道是不是打包原因导致的，报错是在解析抖音请求返回的数据出现的，我随机找了几个直播间都能正常录制，尝试一下添加cookies后是否正常录制

**Comment by espoir1989** [comment]
我也遇到类似的问题了，换了一个ip，正常了

**Comment by xbclub** [comment]
> > > > > v2.31已修复抖音直播录制报错
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/33245941/293322624-6a139268-01c7-4d2e-b6e8-67db115190be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA5MTMsIm5iZiI6MTcwMzkwMDYxMywicGF0aCI6Ii8zMzI0NTk0MS8yOTMzMjI2MjQtNmExMzkyNjgtMDFjNy00ZDJlLWI2ZTgtNjdkYjExNTE5MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWNhZDdhZTU2OTE2YzgyNjAzMzM0MjIxMTNhZDc0YTExOTA2M2RhYzEzOGIwNGE4YjA3OGFkOWQ0ODJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ULDXgwz-lSltB9SZ7DzXyKpiRd0nKSTsBIwDJaIx0s) v2.31 照常报错
> > > 
> > > 
> > > 我这边测试录制没问题，你的直播间id写对了吗，是一串数字那个id
> > 
> > 
> > ```json
> > {
> >   "user": [
> >     {
> >       "platform": "Douyin",
> >       "id": "965952812349",
> >       "name": "ax-1001",
> >       "output": "/data/lubo/ax-1001"
> >     }
> >   ]
> > }
> > ```
> 
> macos系统没测试不知道是不是打包原因导致的，报错是在解析抖音请求返回的数据出现的，我随机找了几个直播间都能正常录制，尝试一下添加cookies后是否正常录制

v2.32测试正常 没有添加cookie
