### ISSUE TITLE
斗鱼录制失败

### ISSUE THREAD

**Issue by lingyuyu** [auqhjjqdo/LiveRecorder#8]
streamlink.exceptions.StreamError:Could not open stream: Unable to open URL: http://hdltc1.douyucdn.cn/live/108780ry5E3s1Sud_4000.flv (403 Client Error: Forbidden for url: http://hdltc1.douyucdn.cn/live/108780ry5E3s1Sud_4000.flv)

**Comment by lingyuyu** [comment]
![QQ图片20230512020508](https://github.com/auqhjjqdo/LiveRecorder/assets/51942824/827a6e19-27ac-44e9-8951-d2cb939c426c)

**Comment by auqhjjqdo** [comment]
已修复，请下载新版本，如有bug欢迎提出

**Comment by lingyuyu** [comment]
![QQ图片20230512031952](https://github.com/auqhjjqdo/LiveRecorder/assets/51942824/3d54e7c3-7c89-4af3-9467-5f201b0edbc5)

**Comment by auqhjjqdo** [comment]
ssl证书错误，你试试把报错里的那个链接复制到播放器打开看看是否能正常播放，可以的话就是暂时网络原因，重试即可

**Comment by lingyuyu** [comment]
播放器打不开

**Comment by auqhjjqdo** [comment]
停止录制后自动重试也会报这个错误吗，或者把代理关掉试试，我这边无法复现该ssl错误

**Comment by lingyuyu** [comment]
是的，停止录制后自动重试也会报这个错误，而且并没有开代理，于是我在腾讯云服务器上安装了一个，结果报错TypeError: 'NoneType' object is not callable
![QQ图片20230513152801](https://github.com/auqhjjqdo/LiveRecorder/assets/51942824/cacf6d5e-3212-4658-89c9-ffa684df8f5e)

**Comment by auqhjjqdo** [comment]
上传一下logs文件夹里的log文件，控制台输出的错误不完整

**Comment by lingyuyu** [comment]
[log_2023-05-13.log](https://github.com/auqhjjqdo/LiveRecorder/files/11469235/log_2023-05-13.log)

**Comment by auqhjjqdo** [comment]
你重新下载一下release里的文件，似乎是有个依赖有问题

**Comment by lingyuyu** [comment]
重新下载后依然有此问题

**Comment by auqhjjqdo** [comment]
修改了一下依赖，麻烦再试试release里更新的版本，如果还是不行的话那就是系统兼容问题了，斗鱼直播比较特殊需要用到js引擎加密数据，python打包可能不完整，需要自己在系统里装node.js环境，或者使用源码运行方式

**Comment by lingyuyu** [comment]
安装了node.js环境后可以正常使用了，感谢
