### ISSUE TITLE
pandalive录制时会挤掉网页端的登录

### ISSUE THREAD

**Issue by xueli12** [auqhjjqdo/LiveRecorder#83]
### 运行环境

版本号：2.3.1
运行平台：win10
运行架构：win10
Python版本：3.11

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:10809",
  "output": "output",
  "user": [
    
    {
      "platform": "Pandalive",
      "id": "4ocari",
      "name": "4ocari",
      "cookies": "",
	  "output": "Q:/KBJ/4ocari",
	  "format": "mp4",
	  "interval": 110
	}
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

谷歌网页端打开了某个主播的页面，然后用程序对该主播录制时，会把网页端的直播间给挤掉。是否需要设置header，应该如何设置呀？
![$1AER0{OI0}X~44MJR%H3JT](https://github.com/auqhjjqdo/LiveRecorder/assets/51438016/20cb75c2-ce5c-4a96-b812-ae47793453a1)

### 错误日志

```Text
[2024-01-11 09:43:27][INFO][__main__][start:47][Pandalive][4ocari]正在检测直播状态
[2024-01-11 09:43:31][INFO][__main__][run_record:135][Pandalive][4ocari]开始录制：[2024.01.11 09.43.31][Pandalive][4ocari]19ㅂ)G컵ㅈㅁ도둑 몸매자랑♡.ts
[2024-01-11 09:43:31][INFO][__main__][stream_writer:147][Pandalive][4ocari]获取到直播流链接：[2024.01.11 09.43.31][Pandalive][4ocari]19ㅂ)G컵ㅈㅁ도둑 몸매자랑♡.ts
https://video-weaver.sjc06.hls.live-video.net/v1/playlist/XXXXX.m3u8
[2024-01-11 09:43:33][INFO][__main__][stream_writer:153][Pandalive][4ocari]正在录制：[2024.01.11 09.43.31][Pandalive][4ocari]19ㅂ)G컵ㅈㅁ도둑 몸매자랑♡.ts
```

**Comment by auqhjjqdo** [comment]
我这边注册不了pandalive，无法测试你所说的这种情况，估计是pandalive的后端限制可能解决不了

**Comment by xueli12** [comment]
> 我这边注册不了pandalive，无法测试你所说的这种情况，估计是pandalive的后端限制可能解决不了

如果需要 我发我的账号给你测试如何，但我找不到github的私信入口

**Comment by auqhjjqdo** [comment]
我在v2.32改了下请求的设备标识为手机版，请测试一下是否可用

**Comment by xueli12** [comment]
> 我在v2.32改了下请求的设备标识为手机版，请测试一下是否可用

这个版本一样会出现挤掉网页登录。我试着在同一个电脑同一个浏览器不同窗口打开同一个直播间也会挤掉另一个窗口

**Comment by auqhjjqdo** [comment]
> > 我在v2.32改了下请求的设备标识为手机版，请测试一下是否可用
> 
> 这个版本一样会出现挤掉网页登录。我试着在同一个电脑同一个浏览器不同窗口打开同一个直播间也会挤掉另一个窗口

我试了下，这种情况只在已经打开直播间然后再运行程序才会出现，这个是pandalive的限制，程序开始录制的时候就相当于网页请求打开直播间，会在已经打开的直播间提示从其他设备登录，浏览器刷新一下直播间就能同时观看和录制了，录制不会停止

**Comment by xueli12** [comment]
> > > 我在v2.32改了下请求的设备标识为手机版，请测试一下是否可用
> > 
> > 
> > 这个版本一样会出现挤掉网页登录。我试着在同一个电脑同一个浏览器不同窗口打开同一个直播间也会挤掉另一个窗口
> 
> 我试了下，这种情况只在已经打开直播间然后再运行程序才会出现，这个是pandalive的限制，程序开始录制的时候就相当于网页请求打开直播间，会在已经打开的直播间提示从其他设备登录，浏览器刷新一下直播间就能同时观看和录制了，录制不会停止

是的，如你所说，谢谢啦。
