### ISSUE TITLE
v2.32版本无法录制Pandalive

### ISSUE THREAD

**Issue by pinkzhang** [auqhjjqdo/LiveRecorder#84]
### 运行环境

版本号：v2.32
运行平台：Win11
运行架构：
Python版本：

### 配置文件

```JSON
{
  "output": "output",
  "user": [
    {
      "platform": "Pandalive",
      "id": "daumtj1",
      "name": "daumtj1",
      "cookies": 
    }
    {
      "platform": "Pandalive",
      "id": "qwas33",
      "name": "qwas33",
      "cookies": 
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

v2.32版本无法录制Pandalive，随便找了两个直播间试了一下，都不行，都显示无可用直播源，倒是v2.31版本，在相同的配置下还可以录制Pandalive

### 错误日志

```Text
[2024-01-11 14:18:23][ERROR][__main__][run_record:144][Pandalive][daumtj1]无可用直播源：[2024.01.11 14.18.23][Pandalive][daumtj1]맞방)3배 살려주세요.ts
[2024-01-11 14:20:36][ERROR][__main__][run_record:144][Pandalive][qwas33]无可用直播源：[2024.01.11 14.20.36][Pandalive][qwas33]19금)들어오면 못나가는 방..♥.ts
```

**Comment by auqhjjqdo** [comment]
你用v2.31在登录状态下同时录制两个pandalive直播没有出现花屏问题吗

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/5e2a26bc-c51d-4ccd-a2e6-595e9d8f7828)
由于我这边没法登录pandalive，我随便找的无需登录就能看的直播是能正常录制的，你发的两个主播我打开直播提示需要登录，可能是只有需要登录的直播才会找不到直播源

**Comment by pinkzhang** [comment]
> 你用v2.31在登录状态下同时录制两个pandalive直播没有出现花屏问题吗

我昨天同时录了两个，没有出现花屏，不过我记得之前也确实出现过花屏的情况

**Comment by pinkzhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/84632728/295814712-5e2a26bc-c51d-4ccd-a2e6-595e9d8f7828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTc2MjcsIm5iZiI6MTcwNDk1NzMyNywicGF0aCI6Ii84NDYzMjcyOC8yOTU4MTQ3MTItNWUyYTI2YmMtYzUxZC00Y2NkLWEyZTYtNTk1ZTlkOGY3ODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOTlmZjRkODY2OWVmZGYyYjQ1ODYyZjU0Yjc1ZjhiM2RkNTFjMjkzODU1YzlhY2IyZTNjMWYzMDZiMWQ5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M2_hnuNiPp7Iz8pHlb03wAZta-sELskTJ7NeqmnJM-Y) 由于我这边没法登录pandalive，我随便找的无需登录就能看的直播是能正常录制的，你发的两个主播我打开直播提示需要登录，可能是只有需要登录的直播才会找不到直播源

我录的这俩确实需要登录，但我也把cookies复制到配置文件里了，唯一不同的是，v2.31可以正常录制，但v2.32不行

**Comment by auqhjjqdo** [comment]
已经修复了，请重新下载v2.32

**Comment by pinkzhang** [comment]
> 已经修复了，请重新下载v2.32

嗯嗯好的，感谢修复
