### ISSUE TITLE
输出文件按日期生成文件夹保存

### ISSUE THREAD

**Issue by ripperX309** [auqhjjqdo/LiveRecorder#93]
### 直播平台

全平台

### 需求描述

生成日期命名的文件夹，让输出的文件可以保存在对应日期的文件夹中，如D：\output\date\***.mp4 ，特别时直播流断断续续的时候同日期的文件太多了，保存在同一个文件夹中有点乱

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
文件整理的功能不属于一个直播录制软件该有的功能，如确有需要按日期分类存放录制文件这种特殊需求，请自行修改以下代码，将日期添加到模板字符串中
https://github.com/auqhjjqdo/LiveRecorder/blob/4a83c9485487abff4ac36cbfdce7abe74bbf03dd/live_recorder.py#L149
