### ISSUE TITLE
建议增加账号密码登录功能，避免cookie失效无法录制

### ISSUE THREAD

**Issue by xueli12** [auqhjjqdo/LiveRecorder#94]
### 直播平台

Afreeca等

### 需求描述

最近在录制Afreeca平台时发现，cookie是有有效期的，因此建议增加账号密码登录的方式以作备选更新cookie，在cookie失效时能够用账号密码获取直播流

### 操作步骤（可选）

1.
2.
3.
...

**Comment by auqhjjqdo** [comment]
使用cookies是类似软件的通用做法，大部分直播网站的登录功能都带有加密或人机校验等反制措施，维护成本很高，不考虑支持账号登录功能
