### ISSUE TITLE
能不能增加一个直播网站chzzk.naver.com 这个直播网站的自动录制功能

### ISSUE THREAD

**Issue by Looper0o** [auqhjjqdo/LiveRecorder#95]
### 直播平台

chzzk

### 需求描述

能不能增加一个直播网站chzzk.naver.com 这个直播网站的自动录制功能，谢谢大佬！

### 操作步骤（可选）

1.
2.
3.
...

**Comment by NormanMises** [comment]
同求，streamlink已经有人做了插件不过没合并
