### ISSUE TITLE
Pandalive 配置该如何填写？

### ISSUE THREAD

**Issue by NormanMises** [auqhjjqdo/LiveRecorder#97]
### 运行环境

版本号：
运行平台：win11
运行架构：x64
Python版本：3.12

### 配置文件

```JSON
无
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

作者大大能说下该如何正确配置pandalive的header和cookie 吗？自己光从浏览器复制了验证了的cookie 经常获取不到流

### 错误日志

```Text
无
```

**Comment by jimmy0435** [comment]
這不算Bug吧
header不需要設置，cookie用chrome f12印出document.cookie後，將cookie中的雙引號"前加上\跳脫後整串放到cookies欄位就可以了。
<img width="866" alt="image" src="https://github.com/auqhjjqdo/LiveRecorder/assets/18476557/6cfeebff-bb2d-4a95-93b9-22b274f2f007">

**Comment by auqhjjqdo** [comment]
获取不到流是有什么报错吗，还是说主播开播了但没开始录制

**Comment by NormanMises** [comment]
2024-03-05 12:11:09.590 | ERROR    | __main__:start:54 - pandaex直播检测请求错误
ReadTimeout('')

**Comment by auqhjjqdo** [comment]
> 2024-03-05 12:11:09.590 | ERROR | **main**:start:54 - pandaex直播检测请求错误 ReadTimeout('')

这个是网络请求超时，代理丢包导致的

**Comment by NormanMises** [comment]
哦哦 目前用您的工具好像没出现漏录的情况

**Comment by NormanMises** [comment]
对了 请问可以录afreeca的19+直播吗？我在streamlink自带config里配了账号密码

**Comment by auqhjjqdo** [comment]
> 对了 请问可以录afreeca的19+直播吗？我在streamlink自带config里配了账号密码

理论上填cookies可以实现录制需要登录的直播

**Comment by NormanMises** [comment]
作者大大研究过panda都需要哪些cookies字段吗？
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/38835726/f079c64b-f880-4310-b75b-5b3edd4134d3)
这个这个字段有好多，不知道哪些是多余的
