### ISSUE TITLE
PR一个提取YouTube频道ID的网站

### ISSUE THREAD

**Issue by justdoiting** [auqhjjqdo/LiveRecorder#99]
### 直播平台

YouTube

### 需求描述

不知道为什么F12控制台输ytInitialData.metadata.channelMetadataRenderer.externalId没有返回ID，从别的网站一键获取到了，也方便小白用户

### 操作步骤（可选）

1.复制YouTube直播链接
2.打开网站https://seostudio.tools/zh/youtube-channel-id
3.粘贴链接并提取
4.返回ID
...

### 需求截图（可选）

![image](https://github.com/auqhjjqdo/LiveRecorder/assets/109136320/9160a0a0-6111-4a51-ad0e-094358132325)

**Comment by auqhjjqdo** [comment]
感谢分享，我会将网站放进readme中
在F12中输入`ytInitialData.metadata.channelMetadataRenderer.externalId`并未返回频道id一般是因为频道是从首页或其他频道点击切换到需要录制的频道，这种情况网页并未完全刷新而是用ajax更新网页数据，在需要录制的频道点击浏览器的刷新按钮再去F12输入就能返回
